# Copyright 2026 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import base64
import json
import logging
import os
import time
from typing import Any, Dict, List, Optional, Tuple, Union

import numpy as np
from aiohttp import ClientResponse
from pydantic import BaseModel, field_validator

from inference_perf.apis import InferenceAPIData, InferenceInfo, UnaryResponseMetrics, StreamedResponseMetrics
from inference_perf.payloads import (
    ImageRepresentation,
    MultimodalSpec,
    PreEncodedFramesVideoSpec,
    PreEncodedImageSpec,
    SyntheticAudioSpec,
    SyntheticFramesVideoSpec,
    SyntheticImageSpec,
    SyntheticMp4VideoSpec,
)
from inference_perf.apis.streaming_parser import parse_sse_stream
from inference_perf.config import APIConfig, APIType
from inference_perf.mediagen.pool import get_video_pool
from inference_perf.mediagen.synthesis import generate_jpeg_bytes, generate_mp4_bytes, generate_png_bytes, generate_wav_bytes
from inference_perf.payloads import (
    Audio,
    Audios,
    Image,
    Images,
    RequestBody,
    RequestMetrics,
    Text,
    Video,
    Videos,
)
from inference_perf.utils.custom_tokenizer import CustomTokenizer

logger = logging.getLogger(__name__)

# Heartbeat for multimodal byte materialization. Image / video / audio bytes
# are rendered lazily in workers during to_request_body, and on large runs the
# cumulative cost is the dominant pre-server-call latency. The heartbeat
# surfaces a per-worker cumulative count so the run does not look hung.
_MULTIMODAL_PROGRESS_LOG_INTERVAL_SEC = 10.0
_multimodal_materialized_requests: int = 0
_multimodal_materialized_images: int = 0
_multimodal_materialized_videos: int = 0
_multimodal_materialized_audios: int = 0
_multimodal_materialized_video_frames: int = 0
_last_multimodal_progress_log_time: Optional[float] = None


def _log_multimodal_progress(images: int, videos: int, audios: int, video_frames: int) -> None:
    """Update per-process counters and emit a heartbeat at most every interval."""
    global _multimodal_materialized_requests
    global _multimodal_materialized_images
    global _multimodal_materialized_videos
    global _multimodal_materialized_audios
    global _multimodal_materialized_video_frames
    global _last_multimodal_progress_log_time

    _multimodal_materialized_requests += 1
    _multimodal_materialized_images += images
    _multimodal_materialized_videos += videos
    _multimodal_materialized_audios += audios
    _multimodal_materialized_video_frames += video_frames

    now = time.monotonic()
    if (
        _last_multimodal_progress_log_time is None
        or (now - _last_multimodal_progress_log_time) >= _MULTIMODAL_PROGRESS_LOG_INTERVAL_SEC
    ):
        logger.info(
            "Multimodal datagen progress: materialized %d requests (images=%d, videos=%d, video_frames=%d, audios=%d) (worker pid=%d)",
            _multimodal_materialized_requests,
            _multimodal_materialized_images,
            _multimodal_materialized_videos,
            _multimodal_materialized_video_frames,
            _multimodal_materialized_audios,
            os.getpid(),
        )
        _last_multimodal_progress_log_time = now


# Fields allowed by the OpenAI/vLLM JSON Schema validator for tool parameters.
# Extra fields generated by Pydantic (e.g. 'default', 'title') are stripped.
# Numeric constraints (minimum, maximum, exclusiveMinimum, exclusiveMaximum) and
# array constraints (minItems, maxItems) are intentionally excluded: vLLM's
# xgrammar backend and the llm-d-inference-sim both reject them as unsupported
# additionalProperties. They are irrelevant for load testing — we only need the
# server to accept the tool schema and generate tokens.
_ALLOWED_JSON_SCHEMA_KEYS = {
    "type",
    "description",
    "enum",
    "properties",
    "required",
    "items",
    "anyOf",
    "oneOf",
    "allOf",
    "$ref",
    "const",
    "additionalProperties",
}


def _clean_schema(obj: Any, is_properties_map: bool = False) -> Any:
    """Recursively remove non-standard JSON Schema keys from a parameters dict.

    is_properties_map: when True, obj is the value of a 'properties' key —
    its keys are property names (not schema keywords) and must be preserved.

    vLLM requires every property schema to have a top-level 'type'. When a
    property uses only 'anyOf' (no 'type'), we inject 'type': 'string' as a
    safe fallback so the validator does not reject the tool definition.
    """
    if isinstance(obj, dict):
        if is_properties_map:
            return {k: _clean_schema(v) for k, v in obj.items()}
        cleaned = {}
        for k, v in obj.items():
            if k not in _ALLOWED_JSON_SCHEMA_KEYS:
                continue
            # vLLM/simulator require additionalProperties to be a boolean.
            # Object-valued schemas (e.g. {"type": "string"}) are valid JSON
            # Schema but rejected by the server — coerce to false.
            if k == "additionalProperties" and not isinstance(v, bool):
                v = False
            cleaned[k] = _clean_schema(v, is_properties_map=(k == "properties"))
        # vLLM requires a plain 'type' on every property schema and does not
        # support anyOf/oneOf. Collapse to 'type': 'string' as a safe fallback.
        if "type" not in cleaned:
            cleaned.pop("anyOf", None)
            cleaned.pop("oneOf", None)
            cleaned["type"] = "string"
        elif "anyOf" in cleaned or "oneOf" in cleaned:
            cleaned.pop("anyOf", None)
            cleaned.pop("oneOf", None)
        # vLLM/simulator require "type": "object" schemas to include
        # "properties". Map-like schemas (using only additionalProperties /
        # propertyNames) lack it — inject an empty one.
        if cleaned.get("type") == "object" and "properties" not in cleaned:
            cleaned["properties"] = {}
        return cleaned
    if isinstance(obj, list):
        return [_clean_schema(v) for v in obj]
    return obj


def _clean_parameters(obj: Any) -> Any:
    return _clean_schema(obj)


class ChatMessage(BaseModel):
    role: str
    content: Optional[Union[str, list[dict[str, Any]]]] = None
    reasoning_content: Optional[str] = None
    tool_calls: Optional[List[Dict[str, Any]]] = None
    tool_call_id: Optional[str] = None

    @field_validator("tool_calls")
    @classmethod
    def validate_tool_calls(cls, v: Optional[List[Dict[str, Any]]]) -> Optional[List[Dict[str, Any]]]:
        if v is None:
            return v
        for i, tc in enumerate(v):
            missing = {"id", "type", "function"} - tc.keys()
            if missing:
                raise ValueError(f"tool_calls[{i}] missing required keys: {missing}")
        return v

    def to_dict(self) -> Dict[str, Any]:
        """Serialise to an OpenAI-compatible message dict."""
        msg: Dict[str, Any] = {"role": self.role}
        if self.tool_call_id is not None:
            msg["tool_call_id"] = self.tool_call_id
        if self.tool_calls is not None:
            msg["tool_calls"] = self.tool_calls
            if self.content is not None:
                msg["content"] = self.content
        else:
            msg["content"] = self.content if self.content is not None else ""
        if self.reasoning_content is not None:
            msg["reasoning_content"] = self.reasoning_content
            msg["reasoning"] = self.reasoning_content
        return msg


def _encode_image(width: int, height: int, representation: ImageRepresentation, rng: np.random.Generator) -> Tuple[bytes, str]:
    """Generate image bytes in the requested representation and return ``(bytes, data_url)``."""
    if representation == ImageRepresentation.JPEG:
        raw = generate_jpeg_bytes(width, height, rng)
        return raw, f"data:image/jpeg;base64,{base64.b64encode(raw).decode('ascii')}"
    raw = generate_png_bytes(width, height, rng)
    return raw, f"data:image/png;base64,{base64.b64encode(raw).decode('ascii')}"


def assemble_content(text_str: str, media_items: list[Tuple[dict[str, Any], float]]) -> list[dict[str, Any]]:
    """Weave media blocks into a text prompt at sampled insertion points."""
    if not media_items:
        return [{"type": "text", "text": text_str}]

    media_items.sort(key=lambda x: x[1])
    content: list[dict[str, Any]] = []
    last_idx = 0
    text_len = len(text_str)

    for block, point in media_items:
        point = max(0.0, min(1.0, point))
        idx = int(point * text_len)

        if idx > last_idx:
            content.append({"type": "text", "text": text_str[last_idx:idx]})
            last_idx = idx

        content.append(block)

    if last_idx < text_len:
        content.append({"type": "text", "text": text_str[last_idx:]})

    return content


class ChatCompletionAPIData(InferenceAPIData):
    messages: List[ChatMessage]
    max_tokens: int = 0
    tool_definitions: Optional[List[Dict[str, Any]]] = None

    # Payload-side multimodal spec (sampled per-request). Materialized into the
    # first user message at ``to_request_body`` time using a fresh RNG.
    multimodal_spec: Optional[MultimodalSpec] = None

    # Optional shared prefix carried separately from the user message text.
    # When ``prefix_text`` and/or ``prefix_multimodal_spec`` are set, the wire
    # user message is built as: prefix_content + " " + payload_content.
    # Prefix-side bytes are materialized with deterministic per-instance seeding
    # so that the same spec produces identical wire bytes across requests in a
    # group — required for prefix-cache benchmarks.
    prefix_text: Optional[str] = None
    prefix_multimodal_spec: Optional[MultimodalSpec] = None
    # Identifies which prefix-cache group this request belongs to. Two requests
    # with the same prefix_multimodal_spec AND the same prefix_cache_key render
    # byte-identical prefix media (so the server's prefix cache hits); requests
    # with the same spec but different prefix_cache_key render different bytes
    # (so distinct logical prefixes don't collide in the cache). Left None when
    # there's only one prefix group, which preserves the old single-stream
    # behavior. The shared_prefix datagen sets this to the group id.
    prefix_cache_key: Optional[int] = None

    # Realized per-instance metrics populated by ``to_request_body`` and read
    # by ``process_response`` to build ``RequestMetrics``. Aggregates across
    # prefix-side and payload-side specs.
    realized_images: Optional[Images] = None
    realized_videos: Optional[Videos] = None
    realized_audios: Optional[Audios] = None

    @staticmethod
    def _materialize_multimodal_content(
        text_str: str,
        spec: MultimodalSpec,
        deterministic: bool,
        cache_key: Optional[int] = None,
    ) -> Tuple[list[dict[str, Any]], list[Image], list[Video], list[Audio]]:
        """Materialize bytes from ``spec`` and weave into ``text_str``.

        Returns ``(content_list, images, videos, audios)``. Pure (no mutation
        of class state). ``deterministic=True`` seeds RNGs per-instance from
        spec content + ``cache_key``, yielding identical bytes for identical
        (spec, cache_key) pairs across calls — required for prefix-cache
        benchmarks. ``cache_key`` is ignored when ``deterministic=False``.
        """
        media_items: list[Tuple[dict[str, Any], float]] = []
        image_instances: list[Image] = []
        video_instances: list[Video] = []
        audio_instances: list[Audio] = []
        fresh_rng = np.random.default_rng()

        def _rng_for(*key_parts: object) -> np.random.Generator:
            if not deterministic:
                return fresh_rng
            return np.random.default_rng(hash((cache_key,) + key_parts) & 0xFFFFFFFF)

        for i, img in enumerate(spec.images):
            # Dispatch on the polymorphic image spec subtype for wire emission.
            # ``img.get_metrics(wire_bytes)`` already encodes the per-provenance
            # measurement rule, so each branch just computes ``wire_bytes`` and
            # calls it. Provenance variants still missing a branch raise below.
            if isinstance(img, SyntheticImageSpec):
                raw_bytes, data_url = _encode_image(
                    img.width, img.height, img.representation, _rng_for("img", i, img.width, img.height)
                )
                wire_bytes = len(raw_bytes)
            elif isinstance(img, PreEncodedImageSpec):
                # Bytes are already encoded by the dataset loader; just base64-wrap
                # them, picking the data-URL mime type from the declared representation.
                data_url = f"data:{img.representation.mime_type};base64,{base64.b64encode(img.image_bytes).decode('ascii')}"
                wire_bytes = len(img.image_bytes)
            else:
                raise TypeError(f"Unwired ImageSpec subclass: {type(img).__name__}")
            media_items.append(({"type": "image_url", "image_url": {"url": data_url}}, img.insertion_point))
            image_instances.append(img.get_metrics(wire_bytes))

        for vi, vid in enumerate(spec.videos):
            # Dispatch on the polymorphic spec subtype for wire emission.
            # Metric construction is delegated to ``vid.get_metrics(total_bytes)``
            # so each provenance owns its own measurement rule (synthetic and
            # pre-encoded report real pixel/byte/frame counts; remote/local
            # stubs would return zero-or-declared-dims per their own contract).
            if isinstance(vid, SyntheticMp4VideoSpec):
                if deterministic:
                    # Deterministic mode bypasses the pool — pool sampling is
                    # non-deterministic, and this path is rare (prefix-side
                    # videos in shared-prefix benchmarks) so per-init encode
                    # cost is acceptable.
                    mp4_bytes = generate_mp4_bytes(
                        vid.width, vid.height, vid.frames, _rng_for("vid_mp4", vi, vid.width, vid.height, vid.frames)
                    )
                else:
                    mp4_bytes = get_video_pool().get(vid.width, vid.height, vid.frames)
                data_url = f"data:video/mp4;base64,{base64.b64encode(mp4_bytes).decode('ascii')}"
                media_items.append(({"type": "video_url", "video_url": {"url": data_url}}, vid.insertion_point))
                total_bytes = len(mp4_bytes)
            elif isinstance(vid, SyntheticFramesVideoSpec):
                total_bytes = 0
                for f in range(vid.frames):
                    raw_bytes, data_url = _encode_image(
                        vid.width, vid.height, vid.frame_representation, _rng_for("vid_frame", vi, f, vid.width, vid.height)
                    )
                    media_items.append(({"type": "image_url", "image_url": {"url": data_url}}, vid.insertion_point))
                    total_bytes += len(raw_bytes)
            elif isinstance(vid, PreEncodedFramesVideoSpec):
                mime = vid.frame_representation.mime_type
                total_bytes = 0
                for frame_bytes in vid.frames_bytes:
                    data_url = f"data:{mime};base64,{base64.b64encode(frame_bytes).decode('ascii')}"
                    media_items.append(({"type": "image_url", "image_url": {"url": data_url}}, vid.insertion_point))
                    total_bytes += len(frame_bytes)
            else:
                raise TypeError(f"Unwired VideoSpec subclass: {type(vid).__name__}")
            video_instances.append(vid.get_metrics(total_bytes))

        for aud in spec.audios:
            # Only synthetic audio variants are wire-wired today; pre-encoded,
            # remote, and local-file are in ``AudioSpecUnion`` but raise here
            # until their materializer branches land.
            if not isinstance(aud, SyntheticAudioSpec):
                raise TypeError(f"Unwired AudioSpec subclass: {type(aud).__name__}")
            # WAV generation is deterministic by duration (silent samples), so
            # no RNG is involved.
            wav_bytes = generate_wav_bytes(aud.duration)
            b64_audio = base64.b64encode(wav_bytes).decode("ascii")
            media_items.append(
                ({"type": "input_audio", "input_audio": {"data": b64_audio, "format": "wav"}}, aud.insertion_point)
            )
            audio_instances.append(aud.get_metrics(len(wav_bytes)))

        return assemble_content(text_str, media_items), image_instances, video_instances, audio_instances

    def _build_user_content(self) -> Optional[list[dict[str, Any]]]:
        """Build the wire user-message content from prefix + payload specs.

        Aggregates realized metrics onto ``self`` for ``process_response``.
        Returns ``None`` when no prefix/payload multimodal data is set, in
        which case ``to_request_body`` falls through to the plain text path.
        """
        if self.prefix_multimodal_spec is None and self.multimodal_spec is None and self.prefix_text is None:
            return None

        # Find the first user message text (if any) for payload-side weaving.
        user_text = ""
        for m in self.messages:
            if m.role == "user" and isinstance(m.content, str):
                user_text = m.content
                break

        all_images: list[Image] = []
        all_videos: list[Video] = []
        all_audios: list[Audio] = []

        if self.prefix_multimodal_spec is not None or self.prefix_text is not None:
            prefix_text = self.prefix_text or ""
            if self.prefix_multimodal_spec is not None:
                prefix_content, p_imgs, p_vids, p_auds = self._materialize_multimodal_content(
                    prefix_text, self.prefix_multimodal_spec, deterministic=True, cache_key=self.prefix_cache_key
                )
                all_images.extend(p_imgs)
                all_videos.extend(p_vids)
                all_audios.extend(p_auds)
            else:
                prefix_content = [{"type": "text", "text": prefix_text}] if prefix_text else []
        else:
            prefix_content = []

        if self.multimodal_spec is not None:
            payload_content, q_imgs, q_vids, q_auds = self._materialize_multimodal_content(
                user_text, self.multimodal_spec, deterministic=False
            )
            all_images.extend(q_imgs)
            all_videos.extend(q_vids)
            all_audios.extend(q_auds)
        else:
            payload_content = [{"type": "text", "text": user_text}] if user_text else []

        # Concatenate prefix + payload, inserting a single space between them
        # if both sides have content. Adjacent text blocks are merged.
        if prefix_content and payload_content:
            if prefix_content[-1].get("type") == "text" and payload_content[0].get("type") == "text":
                merged = dict(prefix_content[-1])
                merged["text"] = merged["text"] + " " + payload_content[0]["text"]
                combined = list(prefix_content[:-1]) + [merged] + list(payload_content[1:])
            else:
                combined = list(prefix_content) + [{"type": "text", "text": " "}] + list(payload_content)
        else:
            combined = list(prefix_content) + list(payload_content)

        self.realized_images = Images(count=len(all_images), instances=all_images) if all_images else None
        self.realized_videos = Videos(count=len(all_videos), instances=all_videos) if all_videos else None
        self.realized_audios = Audios(count=len(all_audios), instances=all_audios) if all_audios else None

        _log_multimodal_progress(
            images=len(all_images),
            videos=len(all_videos),
            audios=len(all_audios),
            video_frames=sum(v.frames for v in all_videos),
        )

        return combined

    def _build_request_metrics(self, prompt_len: int, output_len: int) -> RequestMetrics:
        return RequestMetrics(
            text=Text(input_tokens=prompt_len),
            image=self.realized_images,
            video=self.realized_videos,
            audio=self.realized_audios,
        )

    def _resolve_prompt_tokens(self, server_usage: Optional[Dict[str, Any]], tokenizer: CustomTokenizer) -> int:
        """Input tokens as reported by the server, falling back to client-side tokenization.

        Server-reported ``usage.prompt_tokens`` is the source of truth when present —
        it reflects exactly what the server tokenized (including tool definitions and
        chat-template overhead), which client-side tokenization can only approximate.
        """
        prompt_tokens = server_usage.get("prompt_tokens") if server_usage else None
        if prompt_tokens is not None:
            return int(prompt_tokens)
        return self._count_prompt_tokens(tokenizer)

    def get_api_type(self) -> APIType:
        return APIType.Chat

    def get_route(self) -> str:
        return "/v1/chat/completions"

    async def to_request_body(
        self, effective_model_name: str, max_tokens: int, ignore_eos: bool, streaming: bool
    ) -> RequestBody:
        if self.max_tokens == 0:
            self.max_tokens = max_tokens

        # When any multimodal/prefix data is present, build a single combined
        # user message via the orchestrator. Otherwise pass messages through.
        user_content = self._build_user_content()
        if user_content is not None:
            messages: list[dict[str, Any]] = []
            replaced = False
            for m in self.messages:
                if not replaced and m.role == "user":
                    messages.append({"role": "user", "content": user_content})
                    replaced = True
                else:
                    messages.append(m.to_dict())
            if not replaced:
                messages.append({"role": "user", "content": user_content})
        else:
            messages = [m.to_dict() for m in self.messages]

        payload: Dict[str, Any] = {
            "model": effective_model_name,
            "messages": messages,
            "max_tokens": self.max_tokens,
            "ignore_eos": ignore_eos,
            "stream": streaming,
            **({"stream_options": {"include_usage": True}} if streaming else {}),
        }
        if self.tool_definitions:
            tools = []
            for t in self.tool_definitions:
                if "function" in t:
                    # Already in OpenAI nested format: {"type": "function", "function": {...}}
                    # Still clean parameters so anyOf/oneOf schemas are normalised.
                    fn = t["function"]
                    tools.append(
                        {
                            "type": t.get("type", "function"),
                            "function": {
                                "name": fn["name"],
                                "description": fn.get("description"),
                                "parameters": _clean_parameters(fn.get("parameters")),
                            },
                        }
                    )
                else:
                    # Flat format: {"type": "function", "name": ..., "description": ..., "parameters": ...}
                    tools.append(
                        {
                            "type": t["type"],
                            "function": {
                                "name": t["name"],
                                "description": t.get("description"),
                                "parameters": _clean_parameters(t.get("parameters")),
                            },
                        }
                    )
            payload["tools"] = tools
        return payload

    def _count_prompt_tokens(self, tokenizer: CustomTokenizer) -> int:
        # Count text in shared prefix (if any) plus text in each message, plus
        # tool definitions (if any). Only text parts of structured content
        # count — image/video/audio bytes don't contribute to text-token
        # totals here. Tool definitions are serialized the same way they're
        # sent on the wire (see to_request_body) since the server tokenizes
        # them as part of the prompt.
        total = tokenizer.count_tokens(self.prefix_text) if self.prefix_text else 0
        total += sum(
            tokenizer.count_tokens(
                msg.content
                if isinstance(msg.content, str)
                else "".join(
                    part.get("text", "")
                    for part in msg.content
                    if isinstance(part, dict) and part.get("type") in ["text", "input_text"]
                )
            )
            for msg in self.messages
            if msg.content
        )
        if self.tool_definitions:
            total += tokenizer.count_tokens(json.dumps(self.tool_definitions, ensure_ascii=False))
        return total

    async def process_response(
        self, response: ClientResponse, config: APIConfig, tokenizer: CustomTokenizer, lora_adapter: Optional[str] = None
    ) -> InferenceInfo:
        if config.streaming:
            output_text, chunk_times, raw_content, response_chunks, server_usage = await parse_sse_stream(
                response, extract_content=lambda data: data.get("choices", [{}])[0].get("delta", {}).get("content")
            )
            prompt_len = self._resolve_prompt_tokens(server_usage, tokenizer)
            # Generated text is a continuation, not a sequence start: counting it
            # with special tokens would add a BOS the server's completion_tokens
            # never contains.
            output_len = tokenizer.count_tokens(output_text, add_special_tokens=False)
            return InferenceInfo(
                request_metrics=self._build_request_metrics(prompt_len, output_len),
                response_metrics=StreamedResponseMetrics(
                    response_chunks=response_chunks,
                    chunk_times=chunk_times,
                    output_tokens=output_len,
                    output_token_times=chunk_times,
                    server_usage=server_usage,
                ),
                lora_adapter=lora_adapter,
                extra_info={"raw_response": raw_content},
            )

        data = await response.json()
        server_usage = data.get("usage")
        prompt_len = self._resolve_prompt_tokens(server_usage, tokenizer)
        choices = data.get("choices", [])
        if len(choices) == 0:
            return InferenceInfo(
                request_metrics=self._build_request_metrics(prompt_len, 0),
                lora_adapter=lora_adapter,
            )
        output_text = "".join([choice.get("message", {}).get("content", "") for choice in choices])
        output_len = tokenizer.count_tokens(output_text, add_special_tokens=False)
        return InferenceInfo(
            request_metrics=self._build_request_metrics(prompt_len, output_len),
            response_metrics=UnaryResponseMetrics(output_tokens=output_len, server_usage=server_usage),
            lora_adapter=lora_adapter,
        )
