# Copyright 2025 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Reconstruct raw LLM output from parsed API responses for token estimation.

This module helps estimate the actual tokens generated by an LLM by reconstructing
what the raw output likely looked like before being parsed by LiteLLM or other API wrappers.

Supports:
- Text responses
- Tool/function calls
- Mixed responses (text + tool calls)
- Multiple tool calls
"""

import json
from typing import Dict, List, Any, Union, Optional


def reconstruct_llm_output(response_data: Union[str, Dict[str, Any], List[Any]]) -> str:
    """
    Reconstruct the raw LLM output from any parsed response structure.

    This is the main entry point that handles all types of LLM outputs:
    - Pure text responses
    - Tool/function calls
    - Mixed responses (text + tool calls)

    Args:
        response_data: Can be:
            - A JSON string from OTEL trace (gen_ai.output.messages)
            - A parsed dict/list structure
            - OpenAI API response format
            - LiteLLM parsed format

    Returns:
        String representation of the raw LLM output (for token estimation)

    Example:
        >>> otel_output = '[{"role": "assistant", "content": "Hello!"}]'
        >>> raw_output = reconstruct_llm_output(otel_output)
        >>> print(raw_output)
        Hello!
    """

    # Parse if string
    data_to_process: Union[str, Dict[str, Any], List[Any]] = response_data
    if isinstance(response_data, str):
        try:
            parsed_data: Union[Dict[str, Any], List[Any]] = json.loads(response_data)
            data_to_process = parsed_data
        except json.JSONDecodeError:
            # If it's not JSON, assume it's already raw text
            return response_data

    # Extract the message content
    message = _extract_message(data_to_process)

    if not message:
        return ""

    # Reconstruct based on what's in the message
    output_parts = []

    # 1. Handle text content
    text_content = _extract_text_content(message)
    if text_content:
        output_parts.append(text_content)

    # 2. Handle tool calls
    tool_calls = _extract_tool_calls(message)
    if tool_calls:
        for tool_call in tool_calls:
            tool_output = _format_tool_call(tool_call)
            output_parts.append(tool_output)

    return "\n".join(output_parts) if output_parts else ""


def _extract_message(data: Any) -> Optional[Dict[str, Any]]:
    """
    Extract the assistant message from various response formats.

    Handles:
    - List format: [{"role": "assistant", ...}]
    - Dict with message: {"message": {...}}
    - Dict with choices: {"choices": [{"message": {...}}]}
    - Direct message dict: {"role": "assistant", ...}
    """
    if isinstance(data, list):
        # Find the assistant message
        for item in data:
            if isinstance(item, dict) and item.get("role") == "assistant":
                return item
        # If no role specified, return first item
        if data and isinstance(data[0], dict):
            return data[0]

    elif isinstance(data, dict):
        # Check for OpenAI choices format
        if "choices" in data and data["choices"]:
            choice: Any = data["choices"][0]
            if "message" in choice:
                result: Dict[str, Any] = choice["message"]
                return result
            # Cast choice to Dict[str, Any] since we know it's a dict at this point
            choice_dict: Dict[str, Any] = choice
            return choice_dict

        # Check for direct message key
        if "message" in data:
            msg: Dict[str, Any] = data["message"]
            return msg

        # Check if data itself is a message
        if "role" in data or "content" in data or "parts" in data or "tool_calls" in data:
            return data

    return None


def _extract_text_content(message: Dict[str, Any]) -> str:
    """
    Extract text content from a message.

    Handles:
    - content field (string)
    - content field (list of content parts)
    - parts field (OTEL format)
    """
    text_parts = []

    # Check for direct content field
    if "content" in message:
        content = message["content"]

        if isinstance(content, str):
            if content:  # Only add non-null, non-empty strings
                text_parts.append(content)

        elif isinstance(content, list):
            # Handle content as list of parts
            for part in content:
                if isinstance(part, dict):
                    if part.get("type") == "text" and "text" in part:
                        text_parts.append(part["text"])
                    elif "text" in part:
                        text_parts.append(part["text"])
                elif isinstance(part, str):
                    text_parts.append(part)

    # Check for parts field (OTEL format)
    if "parts" in message:
        for part in message["parts"]:
            if isinstance(part, dict):
                if part.get("type") == "text" and "text" in part:
                    text_parts.append(part["text"])
                elif part.get("type") == "text" and "content" in part:
                    text_parts.append(part["content"])

    return "\n".join(text_parts)


def _extract_tool_calls(message: Dict[str, Any]) -> List[Dict[str, Any]]:
    """
    Extract tool calls from a message.

    Handles:
    - tool_calls field (OpenAI format)
    - parts with type="tool_call" (OTEL format)
    - function_call field (legacy OpenAI format)
    """
    tool_calls = []

    # Check for tool_calls field (OpenAI format)
    if "tool_calls" in message and message["tool_calls"]:
        for tc in message["tool_calls"]:
            if isinstance(tc, dict):
                # OpenAI format: {"id": "...", "type": "function", "function": {"name": "...", "arguments": "..."}}
                if "function" in tc:
                    tool_calls.append(
                        {"id": tc.get("id"), "name": tc["function"].get("name"), "arguments": tc["function"].get("arguments")}
                    )
                # Direct format: {"name": "...", "arguments": "..."}
                elif "name" in tc:
                    tool_calls.append(tc)

    # Check for parts field (OTEL format)
    if "parts" in message:
        for part in message["parts"]:
            if isinstance(part, dict) and part.get("type") == "tool_call":
                tool_calls.append({"id": part.get("id"), "name": part.get("name"), "arguments": part.get("arguments")})

    # Check for legacy function_call field
    if "function_call" in message and message["function_call"]:
        fc = message["function_call"]
        if isinstance(fc, dict):
            tool_calls.append({"name": fc.get("name"), "arguments": fc.get("arguments")})

    return tool_calls


def _format_tool_call(tool_call: Dict[str, Any]) -> str:
    """
    Format a tool call as the LLM would have generated it.

    Uses special token format which is closest to what models actually generate.
    """
    function_name = tool_call.get("name", "unknown_function")
    arguments = tool_call.get("arguments", "{}")

    # If arguments is a dict, serialize it
    if isinstance(arguments, dict):
        arguments = json.dumps(arguments, indent=2)

    # Format with special tokens (most accurate for token counting)
    return f"<|tool_call|>{function_name}<|tool_args|>{arguments}<|end|>"


def reconstruct_each_part_in_message_info(message_info: Dict[str, Any]) -> Dict[str, Any]:
    # towards matching output messages with input messages, transform each part to a stand alone text message
    message_info["parts_text"] = []
    if "parts" not in message_info:
        return message_info
    for part in message_info["parts"]:
        if part["type"] == "tool_call":
            message_info["parts_text"].append(_format_tool_call(part))
        else:
            message_info["parts_text"].append(part["content"])
    return message_info


def reconstruct_llm_input(input_message: Union[str, Dict[str, Any]]) -> str:
    """
    Reconstruct the raw LLM input from a single parsed message structure.

    This function takes a single message from gen_ai.input.messages field from OTEL traces
    and reconstructs what the actual message content text would look like, handling:
    - Complex nested content structures
    - Tool calls and tool results
    - Escaped strings and JSON structures

    Note: This returns ONLY the content text, without role prefixes.

    Args:
        input_message: Can be:
            - A JSON string representing a single message
            - A single message dict

    Returns:
        String representation of the message content (for token estimation)

    Example:
        >>> otel_input = '{"role": "user", "content": "Hello"}'
        >>> raw_input = reconstruct_llm_input(otel_input)
        >>> print(raw_input)
        Hello
    """
    # Parse if string
    message_to_process: Union[str, Dict[str, Any]] = input_message
    if isinstance(input_message, str):
        try:
            parsed_input: Dict[str, Any] = json.loads(input_message)
            message_to_process = parsed_input
        except json.JSONDecodeError:
            # If it's not JSON, return as-is
            return input_message

    if not isinstance(message_to_process, dict):
        return ""

    # Extract content (no role prefix)
    content = message_to_process.get("content")

    if content is None:
        # Check for parts field (OTEL format)
        if "parts" in message_to_process:
            return _extract_content_from_parts(message_to_process["parts"])

        # Check for tool_calls field (assistant messages with only tool calls)
        if "tool_calls" in message_to_process:
            tool_calls = _extract_tool_calls(message_to_process)
            if tool_calls:
                return "\n".join(_format_tool_call(tc) for tc in tool_calls)

        return ""
    elif isinstance(content, str):
        return content
    elif isinstance(content, list):
        # Handle content as list of parts
        return _extract_content_from_list(content)

    return ""


def _extract_content_from_parts(parts: List[Dict[str, Any]]) -> str:
    """Extract text content from OTEL parts format."""
    content_parts = []

    for part in parts:
        if not isinstance(part, dict):
            continue

        part_type = part.get("type", "")

        if part_type == "text":
            # Text content
            if "text" in part:
                content_parts.append(part["text"])
            elif "content" in part:
                content_parts.append(part["content"])

        elif part_type == "tool_call":
            # Tool call (OTEL output format)
            tool_name = part.get("name", "unknown_tool")
            tool_args = part.get("arguments", "{}")
            if isinstance(tool_args, dict):
                tool_args = json.dumps(tool_args, indent=2)
            content_parts.append(f"<|tool_call|>{tool_name}<|tool_args|>{tool_args}<|end|>")

        elif part_type == "tool_result":
            # Tool result
            tool_id = part.get("tool_use_id", "unknown")
            result_content = part.get("content", "")
            is_error = part.get("is_error", False)
            error_marker = " [ERROR]" if is_error else ""
            content_parts.append(f"<tool_result: {tool_id}{error_marker}>\n{result_content}\n</tool_result>")

        elif part_type == "tool_use":
            # Tool use (input format - same as tool_call)
            tool_name = part.get("name", "unknown_tool")
            tool_input = part.get("input", {})
            if isinstance(tool_input, dict):
                tool_input = json.dumps(tool_input, indent=2)
            content_parts.append(f"<|tool_call|>{tool_name}<|tool_args|>{tool_input}<|end|>")

    return "\n".join(content_parts)


def _extract_content_from_list(content_list: List[Any]) -> str:
    """Extract text content from content list format."""
    content_parts = []

    for item in content_list:
        if isinstance(item, str):
            content_parts.append(item)
        elif isinstance(item, dict):
            item_type = item.get("type", "")

            if item_type == "text":
                if "text" in item:
                    content_parts.append(item["text"])
                elif "content" in item:
                    content_parts.append(item["content"])

            elif item_type == "tool_result":
                tool_id = item.get("tool_use_id", "unknown")
                result_content = item.get("content", "")
                is_error = item.get("is_error", False)
                error_marker = " [ERROR]" if is_error else ""
                content_parts.append(f"<tool_result: {tool_id}{error_marker}>\n{result_content}\n</tool_result>")

            elif item_type == "tool_use":
                tool_name = item.get("name", "unknown_tool")
                tool_input = item.get("input", {})
                if isinstance(tool_input, dict):
                    tool_input = json.dumps(tool_input, indent=2)
                content_parts.append(f"<|tool_call|>{tool_name}<|tool_args|>{tool_input}<|end|>")

            # Handle other dict formats
            elif "text" in item:
                content_parts.append(item["text"])
            elif "content" in item:
                content_parts.append(str(item["content"]))

    return "\n".join(content_parts)


def estimate_token_count(text: str, chars_per_token: float = 4.0) -> int:
    """
    Estimate token count from text using character-based heuristic.

    Args:
        text: The text to estimate tokens for
        chars_per_token: Average characters per token (default 4.0 for English)

    Returns:
        Estimated token count
    """
    return int(len(text) / chars_per_token)


def reconstruct_with_token_estimate(
    response_data: Union[str, Dict[str, Any], List[Any]], chars_per_token: float = 4.0
) -> Dict[str, Any]:
    """
    Reconstruct LLM output and provide token estimate.

    Args:
        response_data: The parsed response data
        chars_per_token: Characters per token for estimation

    Returns:
        Dict with 'raw_output' and 'estimated_tokens'
    """
    raw_output = reconstruct_llm_output(response_data)
    estimated_tokens = estimate_token_count(raw_output, chars_per_token)

    return {"raw_output": raw_output, "estimated_tokens": estimated_tokens, "character_count": len(raw_output)}


def reconstruct_input_with_token_estimate(
    input_message: Union[str, Dict[str, Any]], chars_per_token: float = 4.0
) -> Dict[str, Any]:
    """
    Reconstruct LLM input and provide token estimate.

    Args:
        input_message: A single input message (dict or JSON string)
        chars_per_token: Characters per token for estimation

    Returns:
        Dict with 'raw_input' and 'estimated_tokens'
    """
    raw_input = reconstruct_llm_input(input_message)
    estimated_tokens = estimate_token_count(raw_input, chars_per_token)

    return {"raw_input": raw_input, "estimated_tokens": estimated_tokens, "character_count": len(raw_input)}


# Example usage and testing
if __name__ == "__main__":
    print("=" * 80)
    print("LLM Output Reconstruction Examples")
    print("=" * 80)

    # Example 1: Pure text response
    print("\n" + "=" * 80)
    print("EXAMPLE 1: Pure Text Response")
    print("=" * 80)

    text_response = '[{"role": "assistant", "content": "Hello! How can I help you today?"}]'
    result = reconstruct_with_token_estimate(text_response)
    print(f"\nOriginal: {text_response}")
    print(f"\nReconstructed Raw Output:\n{result['raw_output']}")
    print(f"\nEstimated tokens: {result['estimated_tokens']}")
    print(f"Character count: {result['character_count']}")

    # Example 2: Tool call (from your OTEL trace)
    print("\n" + "=" * 80)
    print("EXAMPLE 2: Tool Call (OTEL Format)")
    print("=" * 80)

    otel_output = '[{"role": "assistant", "parts": [{"type": "tool_call", "id": "chatcmpl-tool-b3402586117f4c879fe2f1eb640ddf62", "name": "AskUserQuestion", "arguments": "{\\n  \\"questions\\": [\\n    {\\n      \\"header\\": \\"Identity verification\\",\\n      \\"multiSelect\\": false,\\n      \\"options\\": [\\n        {\\n          \\"label\\": \\"Email\\",\\n          \\"description\\": \\"Provide your email address\\"\\n        },\\n        {\\n          \\"label\\": \\"Name+Zip\\",\\n          \\"description\\": \\"Provide your full name and zip code\\"\\n        }\\n      ],\\n      \\"question\\": \\"How would you like to verify your identity for account access?\\"\\n    }\\n  ]\\n}"}], "finish_reason": "stop"}]'

    result = reconstruct_with_token_estimate(otel_output)
    print(f"\nReconstructed Raw Output:\n{result['raw_output']}")
    print(f"\nEstimated tokens: {result['estimated_tokens']}")
    print(f"Character count: {result['character_count']}")

    # Example 3: Mixed response (text + tool call)
    print("\n" + "=" * 80)
    print("EXAMPLE 3: Mixed Response (Text + Tool Call)")
    print("=" * 80)

    mixed_response = {
        "role": "assistant",
        "content": "I'll help you check the weather.",
        "tool_calls": [
            {
                "id": "call_123",
                "type": "function",
                "function": {"name": "get_weather", "arguments": '{"location": "San Francisco", "unit": "celsius"}'},
            }
        ],
    }

    result = reconstruct_with_token_estimate(mixed_response)
    print(f"\nReconstructed Raw Output:\n{result['raw_output']}")
    print(f"\nEstimated tokens: {result['estimated_tokens']}")
    print(f"Character count: {result['character_count']}")

    # Example 4: Multiple tool calls
    print("\n" + "=" * 80)
    print("EXAMPLE 4: Multiple Tool Calls")
    print("=" * 80)

    multiple_tools = {
        "role": "assistant",
        "content": None,
        "tool_calls": [
            {
                "id": "call_1",
                "type": "function",
                "function": {"name": "search_web", "arguments": '{"query": "Python tutorials"}'},
            },
            {
                "id": "call_2",
                "type": "function",
                "function": {"name": "send_email", "arguments": '{"to": "user@example.com", "subject": "Search Results"}'},
            },
        ],
    }

    result = reconstruct_with_token_estimate(multiple_tools)
    print(f"\nReconstructed Raw Output:\n{result['raw_output']}")
    print(f"\nEstimated tokens: {result['estimated_tokens']}")
    print(f"Character count: {result['character_count']}")

    # Example 5: OpenAI API response format
    print("\n" + "=" * 80)
    print("EXAMPLE 5: OpenAI API Response Format")
    print("=" * 80)

    openai_response = {
        "id": "chatcmpl-123",
        "object": "chat.completion",
        "created": 1234567890,
        "model": "gpt-4",
        "choices": [
            {
                "index": 0,
                "message": {"role": "assistant", "content": "The capital of France is Paris."},
                "finish_reason": "stop",
            }
        ],
    }

    result = reconstruct_with_token_estimate(openai_response)
    print(f"\nReconstructed Raw Output:\n{result['raw_output']}")
    print(f"\nEstimated tokens: {result['estimated_tokens']}")
    print(f"Character count: {result['character_count']}")

    print("\n" + "=" * 80)
    print("=" * 80)
    print("INPUT MESSAGE RECONSTRUCTION EXAMPLES")
    print("=" * 80)
    print("=" * 80)

    # Example 6: Simple user message
    print("\n" + "=" * 80)
    print("EXAMPLE 6: Simple User Message")
    print("=" * 80)

    simple_input = '{"role": "user", "content": "What is the capital of France?"}'
    result = reconstruct_input_with_token_estimate(simple_input)
    print(f"\nOriginal: {simple_input}")
    print(f"\nReconstructed Raw Input:\n{result['raw_input']}")
    print(f"\nEstimated tokens: {result['estimated_tokens']}")
    print(f"Character count: {result['character_count']}")

    # Example 7: Assistant message with string content
    print("\n" + "=" * 80)
    print("EXAMPLE 7: Assistant Message")
    print("=" * 80)

    assistant_msg = {"role": "assistant", "content": "I'd be happy to help! Can you provide your order ID?"}
    result = reconstruct_input_with_token_estimate(assistant_msg)
    print(f"\nReconstructed Raw Input:\n{result['raw_input']}")
    print(f"\nEstimated tokens: {result['estimated_tokens']}")
    print(f"Character count: {result['character_count']}")

    # Example 8: Complex message with tool results (from your OTEL trace)
    print("\n" + "=" * 80)
    print("EXAMPLE 8: Message with Tool Results (OTEL Format)")
    print("=" * 80)

    complex_input = {
        "role": "user",
        "content": [{"type": "tool_result", "content": "Answer questions?", "is_error": True, "tool_use_id": "tool-123"}],
    }

    result = reconstruct_input_with_token_estimate(complex_input)
    print(f"\nReconstructed Raw Input:\n{result['raw_input']}")
    print(f"\nEstimated tokens: {result['estimated_tokens']}")
    print(f"Character count: {result['character_count']}")

    # Example 9: System message
    print("\n" + "=" * 80)
    print("EXAMPLE 9: System Message")
    print("=" * 80)

    system_input = {"role": "system", "content": "You are a helpful assistant that provides concise answers."}
    result = reconstruct_input_with_token_estimate(system_input)
    print(f"\nReconstructed Raw Input:\n{result['raw_input']}")
    print(f"\nEstimated tokens: {result['estimated_tokens']}")
    print(f"Character count: {result['character_count']}")

    # Example 10: OTEL parts format
    print("\n" + "=" * 80)
    print("EXAMPLE 10: OTEL Parts Format")
    print("=" * 80)

    otel_parts_input = {
        "role": "assistant",
        "parts": [
            {"type": "text", "text": "I'll check the weather for you."},
            {"type": "tool_call", "id": "call_456", "name": "get_weather", "arguments": '{"location": "Paris"}'},
        ],
    }
    result = reconstruct_input_with_token_estimate(otel_parts_input)
    print(f"\nReconstructed Raw Input:\n{result['raw_input']}")
    print(f"\nEstimated tokens: {result['estimated_tokens']}")
    print(f"Character count: {result['character_count']}")

    print("\n" + "=" * 80)
    print("All examples completed!")
    print("=" * 80)
