# Copyright 2025 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
OTel Trace Replay Data Generator

This module provides a data generator that replays LLM requests from OpenTelemetry trace files.
It processes OTel JSON traces, extracts LLM calls, infers dependencies, and replays them
with proper timing and dependency enforcement.

Output-aware replay
-------------------
When a call has "output" segments (i.e., a predecessor's output was injected as an assistant
message in the original trace), the replayer substitutes the recorded assistant message content
with the *actual* output generated by the predecessor call at replay time.

This ensures that growing-context patterns (multi-turn conversations, agent chains) are replayed
faithfully: the KV cache sees the real generated text, not the static recorded text.

The substitution is performed in `load_lazy_data` using the `EventOutputRegistry`, which maps
event_id → actual output text. All registry data is stored in per-worker plain dicts; session-to-
worker affinity ensures that the event writing an output and the events reading it always run on
the same worker process.

The actual output is captured in `OTelChatCompletionAPIData.process_response`, which overrides
the base `ChatCompletionAPIData.process_response` to register the output after each LLM call.

Cross-process coordination
---------------------------
Two orthogonal coordination problems exist in this system:

  Problem A — intra-worker, between coroutines on the same event loop:
    An event waits for its predecessor's output before building its request.
    Handled by EventOutputRegistry using plain dicts and asyncio.Event.
    No IPC involved; session-to-worker affinity makes cross-process sharing unnecessary.

  Problem B — cross-process, worker → main process:
    The main process needs to know when sessions complete for OTEL span closure and reporting.
    Workers detect session completion and push notifications via mp.Queue.

    - WorkerSessionTracker: Per-worker tracking of event completions and session failures
    - session_completion_queue: Workers push completion data when last event finishes
    - Main process consumes from queue in check_session_completed()

OTelChatCompletionAPIData holds refs to WorkerSessionTracker and completion_queue.
"""

import asyncio
import glob
import json
import logging
import random
import time
from dataclasses import dataclass, field, replace as dc_replace
from multiprocessing.managers import SyncManager
from pathlib import Path
from typing import Any, Dict, List, Optional, Set

from aiohttp import ClientResponse

from inference_perf.apis import (
    ChatCompletionAPIData,
    InferenceAPIData,
    InferenceInfo,
    LazyLoadInferenceAPIData,
    SessionLifecycleMetric,
)
from inference_perf.apis.chat import ChatMessage
from inference_perf.apis.streaming_parser import parse_sse_stream
from inference_perf.config import APIConfig, APIType, DataConfig
from inference_perf.datagen.base import SessionGenerator, LazyLoadDataMixin
from inference_perf.datagen.otel_trace_to_replay_graph import (
    InputSegment,
    ReplayGraph,
    build_raw_calls,
    build_graph,
)
from inference_perf.utils.custom_tokenizer import CustomTokenizer

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# EventFailedError — raised by require_async when a predecessor event failed
# ---------------------------------------------------------------------------


class EventFailedError(Exception):
    """Raised by EventOutputRegistry.require_async when the awaited event failed."""

    def __init__(self, event_id: str) -> None:
        super().__init__(f"Predecessor event {event_id!r} failed")
        self.event_id = event_id


# ---------------------------------------------------------------------------
# SessionGraphState — tracks graph traversal state for one session
# ---------------------------------------------------------------------------


@dataclass
class SessionGraphState:
    """Tracks graph traversal state for one session.

    Manages which events are ready to dispatch, which have been dispatched,
    and which have completed. Used for graph-based traversal.
    """

    session_id: str
    graph: ReplayGraph
    ready_events: Set[str]  # event_ids ready to dispatch (predecessors done)
    dispatched_events: Set[str]  # event_ids already dispatched
    completed_events: Set[str]  # event_ids that have completed
    event_completion_times: Dict[str, float]  # event_id → completion timestamp
    is_active: bool = False  # Is this session currently active?
    is_complete: bool = False  # Has this session finished all events?
    failed: bool = False  # Did this session fail?
    cancelled_events: int = 0  # Number of events cancelled due to failure


# ---------------------------------------------------------------------------
# OTelInferenceInfo — InferenceInfo subclass that carries the output text
# ---------------------------------------------------------------------------


class OTelInferenceInfo(InferenceInfo):
    """InferenceInfo subclass that also carries the raw output text.

    Inherits all fields from InferenceInfo (input_tokens, output_tokens, etc.)
    and adds output_text so the OTel replay path can register the actual
    generated text in the EventOutputRegistry without touching the base class.
    """

    output_text: Optional[str] = None
    output_tokens: int = 0
    output_token_times: list[float] = field(default_factory=list)


# ---------------------------------------------------------------------------
# WorkerSessionTracker — tracks session state within a worker process
# ---------------------------------------------------------------------------


class WorkerSessionTracker:
    """Tracks session state within a single worker process.

    Since all events of a session run on the same worker (session-to-worker affinity),
    each worker can independently track:
    - Which events have completed
    - Whether the session has failed
    - Event completion times

    Session completion is communicated to main process via mp.Queue.
    """

    def __init__(self) -> None:
        """Initialize empty tracking state."""
        # Nested map: session_id -> {event_id -> completion_time}
        self._event_completions: Dict[str, Dict[str, float]] = {}

        # Set of session_ids that have failed
        self._failed_sessions: Set[str] = set()

    def record_event_completed(self, session_id: str, event_id: str, completion_time: float) -> None:
        """Record that an event has completed.

        Args:
            session_id: The session ID
            event_id: The event ID (unqualified, e.g., "event_0")
            completion_time: Wall-clock time when event completed
        """
        if session_id not in self._event_completions:
            self._event_completions[session_id] = {}
        self._event_completions[session_id][event_id] = completion_time

    def is_event_completed(self, session_id: str, event_id: str) -> bool:
        """Check if an event has completed.

        Args:
            session_id: The session ID
            event_id: The event ID (unqualified, e.g., "event_0")

        Returns:
            True if the event has completed
        """
        return session_id in self._event_completions and event_id in self._event_completions[session_id]

    def get_event_completion_time(self, session_id: str, event_id: str) -> Optional[float]:
        """Get the completion time for an event.

        Args:
            session_id: The session ID
            event_id: The event ID (unqualified, e.g., "event_0")

        Returns:
            Completion time, or None if not completed
        """
        return self._event_completions.get(session_id, {}).get(event_id)

    def mark_session_failed(self, session_id: str) -> None:
        """Mark a session as failed.

        Args:
            session_id: The session ID
        """
        self._failed_sessions.add(session_id)

    def is_session_failed(self, session_id: str) -> bool:
        """Check if a session has failed.

        Args:
            session_id: The session ID

        Returns:
            True if the session has failed
        """
        return session_id in self._failed_sessions

    def get_session_event_count(self, session_id: str) -> int:
        """Get the number of completed events for a session.

        Args:
            session_id: The session ID

        Returns:
            Number of completed events
        """
        return len(self._event_completions.get(session_id, {}))

    def get_session_completion_times(self, session_id: str) -> Dict[str, float]:
        """Get all event completion times for a session.

        Args:
            session_id: The session ID

        Returns:
            Dict mapping event_id to completion_time
        """
        return self._event_completions.get(session_id, {}).copy()


# ---------------------------------------------------------------------------
# EventOutputRegistry — intra-worker output and message store
# ---------------------------------------------------------------------------


class EventOutputRegistry:
    """Per-worker registry mapping event_id → actual output text and input messages.

    All data is stored in plain in-process dicts. Session-to-worker affinity
    guarantees that the event writing an output and the events reading it always
    run on the same worker process, so no IPC is needed here.

    Async waiting between coroutines on the same event loop is handled via
    asyncio.Event — one per event, allocated on first demand.

    This class has no Manager dependency. Cross-process communication for session
    completion is handled via mp.Queue, not shared state.

    Usage:
        registry = EventOutputRegistry()
        # workers call registry.record(event_id, text, messages) after each LLM call
        # dependent events call await registry.require_async(event_id) before dispatching
    """

    def __init__(self) -> None:
        # Output text and input messages: plain dicts, same-worker only.
        self._event_output_text: Dict[str, str] = {}
        self._event_input_messages: Dict[str, Any] = {}

        # One asyncio.Event per session event. Only accessed from coroutines on this
        # worker's single event loop; no lock needed.
        self._event_signals: Dict[str, asyncio.Event] = {}

        # Set of event_ids that failed. record_failure() adds here and sets the
        # event's signal so waiting coroutines wake and raise EventFailedError.
        self._failed_event_ids: Set[str] = set()

    def record(self, event_id: str, output_text: str, messages: List[Any]) -> None:
        """Register output for a completed event and wake any async waiters.

        Raises:
            ValueError: If event_id has already been recorded (events should only complete once)
        """
        if event_id in self._event_output_text:
            raise ValueError(
                f"Event {event_id} has already been recorded. "
                f"Each event should only complete once. This indicates a bug in the replay logic."
            )

        self._event_output_text[event_id] = output_text
        # Always store messages, even if empty list - successors may need to know the event completed
        self._event_input_messages[event_id] = list(messages) if messages else []

        # Signal any coroutine waiting on this event (same worker only).
        if event_id in self._event_signals:
            self._event_signals[event_id].set()
            logger.debug(f"Set asyncio.Event signal for event {event_id}")

    def get_output_by_event_id(self, event_id: str) -> Optional[str]:
        """Return the output text for a given event_id, or None if not yet registered."""
        return self._event_output_text.get(event_id)

    def get_messages_by_event_id(self, event_id: str) -> Optional[List[Any]]:
        """Return the input messages for a given event_id.

        Args:
            event_id: The event ID to look up

        Returns:
            List of input messages, or None if not found
        """
        return self._event_input_messages.get(event_id)

    def get_event_ids(self) -> List[str]:
        """Return all registered event IDs.

        Returns:
            List of all event IDs that have registered outputs
        """
        return list(self._event_output_text.keys())

    def record_failure(self, event_id: str) -> None:
        """Mark an event as failed and wake any async waiters with a failure signal.

        Idempotent: calling multiple times for the same event is safe.
        Only sets the signal — does not write to _event_output_text.
        """
        self._failed_event_ids.add(event_id)
        if event_id not in self._event_signals:
            self._event_signals[event_id] = asyncio.Event()
        self._event_signals[event_id].set()
        logger.debug(f"Recorded failure for event {event_id}")

    def is_event_failed(self, event_id: str) -> bool:
        """Return True if this event has been marked as failed."""
        return event_id in self._failed_event_ids

    async def require_async(self, event_id: str, timeout_sec: float = 3600.0) -> str:
        """Wait asynchronously for an event's output.

        If the output is already available, returns immediately. Otherwise suspends
        the calling coroutine until record() is called for this event_id, then resumes.

        Raises:
            EventFailedError: if the event failed (via record_failure)
            TimeoutError: if output not available within timeout_sec
        """
        # Fast path: predecessor already failed.
        if event_id in self._failed_event_ids:
            raise EventFailedError(event_id)

        # Fast path: predecessor already completed.
        output = self._event_output_text.get(event_id)
        if output is not None:
            return output

        # Create the signal before any await point. Because asyncio is cooperative,
        # record() cannot run between this line and the event.wait() below, so there
        # is no window where the signal could be set before we start waiting.
        if event_id not in self._event_signals:
            self._event_signals[event_id] = asyncio.Event()
        signal = self._event_signals[event_id]

        # Second fast-path checks: no await has occurred since the first checks,
        # but be defensive in case this method's call site changes in the future.
        if event_id in self._failed_event_ids:
            raise EventFailedError(event_id)
        output = self._event_output_text.get(event_id)
        if output is not None:
            return output

        logger.debug(f"Event {event_id} waiting on asyncio signal (zero threads)")

        try:
            await asyncio.wait_for(signal.wait(), timeout=timeout_sec)
        except asyncio.TimeoutError as e:
            raise TimeoutError(
                f"EventOutputRegistry: output for '{event_id}' not available after "
                f"{timeout_sec:.1f}s. Check that the predecessor is not blocked or failed."
            ) from e

        # Check if the signal was fired due to failure.
        if event_id in self._failed_event_ids:
            raise EventFailedError(event_id)

        # record() writes _event_output_text before calling signal.set(). Both run on
        # the same single-threaded event loop, so the value is guaranteed to be present here.
        output = self._event_output_text.get(event_id)
        assert output is not None, (
            f"asyncio signal fired for {event_id} but output missing from local cache — this is a bug in record()"
        )
        logger.debug(f"Event {event_id} woke from asyncio signal")
        return output


# ---------------------------------------------------------------------------
# OTelChatCompletionAPIData — captures output and registers it in the registry
# ---------------------------------------------------------------------------


class OTelChatCompletionAPIData(ChatCompletionAPIData):
    """ChatCompletionAPIData subclass for OTel trace replay.

    Overrides process_response to:
    1. Extract the actual output text from the LLM response.
    2. Register it in the EventOutputRegistry under this call's event_id.
    3. Return OTelInferenceInfo (InferenceInfo subclass) with output_text populated.

    The registry and event_id are passed at construction time via Pydantic fields.
    arbitrary_types_allowed is required because EventOutputRegistry and
    WorkerSessionTracker are not Pydantic models.

    Dependency handling:
    - predecessor_event_ids: List of events that must complete before this one
    - wait_ms: Additional delay after predecessors complete
    - input_segments: Segment decomposition for output substitution
    - original_messages: Original messages before substitution (used as template)
    """

    model_config = {"arbitrary_types_allowed": True}

    event_id: str
    registry: EventOutputRegistry
    worker_tracker: WorkerSessionTracker

    # Session completion notification
    completion_queue: Any  # mp.Queue for notifying main process
    total_events_in_session: int  # Total number of events in this session

    # Dependency information for async waiting
    predecessor_event_ids: List[str] = field(default_factory=list)
    wait_ms: int = 0
    input_segments: List[InputSegment] = field(default_factory=list)
    original_messages: List[Dict[str, Any]] = field(default_factory=list)
    expected_output_content: Optional[str] = None

    # Flag to skip HTTP request (set when session fails)
    skip_request: bool = False

    def _extract_session_id(self) -> str:
        """Extract session_id from qualified event_id.

        Returns:
            The session_id portion of the event_id
        """
        return self.event_id.split(":")[0] if ":" in self.event_id else self.event_id

    async def wait_for_predecessors_and_substitute(self) -> None:
        """Wait for all predecessor events to complete, then substitute output segments.

        Called by the worker before dispatching the HTTP request. Each predecessor
        is awaited via asyncio.Event, so the coroutine suspends without consuming
        any OS threads. All predecessors are waited in parallel via asyncio.gather.

        If any predecessor failed, EventFailedError is raised by require_async, caught
        here, and propagated by calling registry.record_failure(self.event_id) so that
        this event's own successors also wake and skip without making HTTP requests.

        Requires all events of this session to run on the same worker, which is
        enforced by session-to-worker affinity in get_session_events().
        """
        # Extract session_id from event_id (format: "session_id:event_xxx")
        session_id = self._extract_session_id()

        # Pre-wait check: if session already failed, skip immediately.
        if self.worker_tracker.is_session_failed(session_id):
            logger.info(f"Event {self.event_id} skipping - session {session_id} has failed (pre-wait check)")
            self.skip_request = True
            self.registry.record_failure(self.event_id)
            return

        if self.predecessor_event_ids:
            logger.debug(f"Event {self.event_id} waiting for {len(self.predecessor_event_ids)} predecessor(s)")
            try:
                await asyncio.gather(
                    *[self.registry.require_async(event_id, timeout_sec=3600.0) for event_id in self.predecessor_event_ids]
                )
            except EventFailedError:
                logger.info(f"Event {self.event_id} skipping - predecessor failed")
                self.skip_request = True
                self.registry.record_failure(self.event_id)
                return
            logger.debug(f"Event {self.event_id} all predecessors done")

        # Wait additional delay specified in wait_ms
        if self.wait_ms > 0:
            wait_sec = self.wait_ms / 1000.0
            logger.debug(f"Event {self.event_id} waiting {wait_sec:.3f}s (wait_ms={self.wait_ms})")
            await asyncio.sleep(wait_sec)

        # Substitute output segments with actual predecessor outputs.
        if any(seg.type == "output" or seg.type == "shared" for seg in self.input_segments):
            logger.debug(f"Event {self.event_id} substituting output/shared segments")
            substituted = self._build_messages_with_substitution()
            self.messages = [ChatMessage(role=m["role"], content=m["content"]) for m in substituted]
            logger.debug(f"Event {self.event_id} substitution complete, {len(self.messages)} messages")

    def _build_messages_with_substitution(self) -> List[Dict[str, Any]]:
        """Build messages with output segments substituted with actual predecessor outputs.

        For assistant messages, we substitute their output messages with the actual output.
        """
        if not self.input_segments:
            return self.original_messages

        result = []
        cursor = 0

        for seg in self.input_segments:
            seg_msgs = self.original_messages[cursor : cursor + seg.message_count]

            if seg.type == "output":
                # Output segment: substitute with actual output from the specific predecessor
                if seg.source_event_id:
                    actual_output = self.registry.get_output_by_event_id(seg.source_event_id)
                    logger.debug(
                        f"Registry get for event {self.event_id} output segment from {seg.source_event_id} generated: {actual_output}"
                    )

                    if actual_output:
                        for msg in seg_msgs:
                            substituted = dict(msg)
                            substituted["content"] = actual_output
                            result.append(substituted)
                        logger.debug(
                            f"Event {self.event_id}: substituted output segment with actual output from {seg.source_event_id}"
                        )
                    else:
                        logger.warning(
                            f"Event {self.event_id}: output segment from {seg.source_event_id} "
                            f"not available, using recorded content"
                        )
                        result.extend(seg_msgs)
                else:
                    logger.warning(f"Event {self.event_id}: output segment has no source_event_id, using recorded content")
                    result.extend(seg_msgs)
            elif seg.type == "shared":
                if seg.source_event_id is None:
                    logger.error(f"CRITICAL: Event {self.event_id} shared segment has no source_event_id")
                    result.extend(seg_msgs)
                    continue
                seg_msgs_from_parent = self.registry.get_messages_by_event_id(seg.source_event_id)
                if seg_msgs_from_parent is None:
                    logger.error(
                        f"CRITICAL: Event {self.event_id} shared segment from {seg.source_event_id} "
                        f"has no messages in registry (should not happen after require_async)"
                    )
                    # Fallback to original messages
                    result.extend(seg_msgs)
                else:
                    logger.debug(
                        f"Registry get for event {self.event_id} from {seg.source_event_id} "
                        f"shared segment num messages in parent event: {len(seg_msgs_from_parent)}"
                    )
                    if len(seg_msgs_from_parent) != len(seg_msgs):
                        logger.error(
                            f"Event {self.event_id} shared segment from {seg.source_event_id} "
                            f"had different number of messages in parent event: {len(seg_msgs_from_parent)}, "
                            f"num messages in seg: {len(seg_msgs)}"
                        )
                    for msg in seg_msgs_from_parent:
                        result.append(dict(msg))
            elif seg.type == "unique":
                # Unique message, keep as-is
                for msg in seg_msgs:
                    result.append(msg)
            else:
                # Unknown segment type, keep as-is
                result.extend(seg_msgs)

            cursor += seg.message_count

        return result

    def on_completion(self, info: InferenceInfo) -> None:
        """Called after every request completes (real or mock) to register output and unblock successors."""
        output_text = info.output_text if isinstance(info, OTelInferenceInfo) else ""
        output_text = output_text or ""
        self.registry.record(self.event_id, output_text, self.messages)
        logger.debug(
            f"calling registry record for event {self.event_id} num input messages {len(self.messages)} and output: {output_text}"
        )
        completion_time = time.perf_counter()
        session_id = self._extract_session_id()
        event_id = self.event_id.split(":", 1)[1] if ":" in self.event_id else self.event_id
        self.worker_tracker.record_event_completed(session_id, event_id, completion_time)
        logger.debug(f"Recorded event completion in worker tracker for {self.event_id}")

        # Check if this was the last event in the session
        completed_count = self.worker_tracker.get_session_event_count(session_id)

        if completed_count == self.total_events_in_session:
            # Session complete! Notify main process via queue
            logger.debug(f"Session {session_id} completed all {self.total_events_in_session} events in worker")

            # Gather completion data (event_ids are already unqualified in nested structure)
            completion_data = {
                "session_id": session_id,
                "completion_time": completion_time,
                "failed": self.worker_tracker.is_session_failed(session_id),
                "event_completion_times": self.worker_tracker.get_session_completion_times(session_id),
            }

            # Push to queue for main process
            if self.completion_queue is not None:
                try:
                    self.completion_queue.put_nowait(completion_data)
                    logger.debug(f"Pushed session {session_id} completion to queue")
                except Exception as e:
                    logger.error(f"Failed to push session {session_id} completion to queue: {e}")

    async def process_response(
        self,
        response: ClientResponse,
        config: APIConfig,
        tokenizer: CustomTokenizer,
        lora_adapter: Optional[str] = None,
    ) -> OTelInferenceInfo:
        """Process the LLM response, capture output text, and register it."""
        logger.debug(f"process_response called for event {self.event_id}")
        output_text: str = ""

        if config.streaming:
            # Use shared streaming parser with chat-specific content extraction
            output_text, output_token_times, raw_content, _, _ = await parse_sse_stream(
                response, extract_content=lambda data: data.get("choices", [{}])[0].get("delta", {}).get("content")
            )

            prompt_text = "".join([msg.content for msg in self.messages if msg.content])
            prompt_len = tokenizer.count_tokens(prompt_text)
            output_len = tokenizer.count_tokens(output_text)
            info = OTelInferenceInfo(
                input_tokens=prompt_len,
                output_tokens=output_len,
                output_token_times=output_token_times,
                lora_adapter=lora_adapter,
                output_text=output_text or None,
                extra_info={"raw_response": raw_content},
            )
        else:
            data = await response.json()
            prompt_len = tokenizer.count_tokens("".join([m.content for m in self.messages]))
            choices = data.get("choices", [])
            if choices:
                output_text = "".join([choice.get("message", {}).get("content", "") for choice in choices])
            output_len = tokenizer.count_tokens(output_text)
            info = OTelInferenceInfo(
                input_tokens=prompt_len,
                output_tokens=output_len,
                lora_adapter=lora_adapter,
                output_text=output_text or None,
            )

        # Register output and notify successors.
        self.on_completion(info)

        if output_text:
            logger.debug(f"Registered output for event {self.event_id}: {len(output_text)} chars : {output_text}")
        else:
            logger.debug(f"Registered empty output for event {self.event_id}")

        return info

    async def process_failure(
        self,
        response: Optional[ClientResponse],
        config: APIConfig,
        tokenizer: CustomTokenizer,
        exception: Exception,
        lora_adapter: Optional[str] = None,
    ) -> InferenceInfo:
        """Process a failed request and signal failure to main process.

        This method is called when:
        1. An exception occurs (network error, timeout, etc.)
        2. An HTTP error occurs (status != 200)

        It signals the failure to the main process via shared state,
        then calls on_completion() to unblock dependent events.

        Args:
            response: The HTTP response (may be None for network errors)
            config: API configuration
            tokenizer: Tokenizer for token counting
            exception: The exception that occurred
            lora_adapter: Optional LoRA adapter name

        Returns:
            OTelInferenceInfo with empty output
        """
        logger.error(f"Request failed for event {self.event_id}: {type(exception).__name__}: {str(exception)}")

        # Extract session_id from event_id (format: "session_id:event_xxx")
        session_id = self._extract_session_id()

        # Check if session was already marked as failed (to avoid duplicate notifications)
        was_already_failed = self.worker_tracker.is_session_failed(session_id)

        # Mark the entire session as failed to prevent other events from processing
        self.worker_tracker.mark_session_failed(session_id)

        # Signal failure to any successors waiting in require_async.
        self.registry.record_failure(self.event_id)

        # Immediately notify main process of session failure (only once per session)
        # This ensures the main process doesn't wait for all events to complete
        if not was_already_failed and self.completion_queue is not None:
            completion_time = time.perf_counter()
            completed_so_far = self.worker_tracker.get_session_event_count(session_id)
            cancelled = self.total_events_in_session - completed_so_far - 1  # -1 for the failing event itself
            completion_data = {
                "session_id": session_id,
                "completion_time": completion_time,
                "failed": True,
                "cancelled_events": cancelled,
                "event_completion_times": self.worker_tracker.get_session_completion_times(session_id),
            }

            try:
                logger.debug(f"Pushing immediate failure notification for session {session_id}")
                self.completion_queue.put_nowait(completion_data)
                logger.info(f"Session {session_id} failure notification sent to main process (cancelled_events={cancelled})")
            except Exception as e:
                logger.error(f"Failed to push session {session_id} failure notification to queue: {e}")

        return OTelInferenceInfo(
            input_tokens=0,
            output_tokens=0,
            lora_adapter=lora_adapter,
            output_text="",
        )


# ---------------------------------------------------------------------------
# OTelTraceReplayEvent — one entry per graph event
# ---------------------------------------------------------------------------


@dataclass
class OTelTraceReplayEvent:
    """Represents a single LLM request event from an OTel trace, derived from a GraphCall."""

    call_id: str
    event_id: str
    file_index: int
    t_start_ms: int  # event start time (adjusted for time_scale + session offset)
    t_end_ms: int  # event end time
    model: str
    messages: List[Dict[str, Any]]  # original (recorded) messages — used as template
    expected_output: str
    input_segments: List[InputSegment]  # segment decomposition for output substitution
    expected_output_tokens: int
    temperature: Optional[float]
    max_tokens_recorded: Optional[int]
    # Predecessor event IDs (events that must complete before this one starts)
    predecessor_event_ids: List[str] = field(default_factory=list)
    wait_ms: int = 0


@dataclass
class OTelTraceSession:
    """Represents a complete session (one OTel file) as a ReplayGraph."""

    session_id: str
    file_path: Path
    file_index: int
    graph: ReplayGraph
    start_offset_ms: int = 0  # Offset for staggered session starts


def resolve_trace_files(trace_files: List[str]) -> List[Path]:
    """
    Extract all relevant files from a list of paths.

    Handles two types of paths:
    1. Full path to a Otel file: /path/to/file.json
    2. Wildcard pattern: /path/to/*.json

    Args:
        trace_files: List of file paths or wildcard patterns

    Returns:
        List of resolved file paths (duplicates removed, sorted)

    Example:
        >>> paths = [
        ...     "/data/config.json",
        ...     "/logs/*.json",
        ...     "/output/**/*.json"  # recursive pattern
        ... ]
        >>> files = resolve_trace_files(paths)
    """
    all_files = set()  # Use set to avoid duplicates

    for path_pattern in trace_files:
        # Check if path contains wildcard characters
        if "*" in path_pattern or "?" in path_pattern:
            # Use glob to expand the pattern
            # recursive=True enables ** pattern for recursive matching
            matched_files = glob.glob(path_pattern, recursive=True)

            # Filter to only include files (not directories)
            for matched in matched_files:
                if Path(matched).is_file():
                    all_files.add(matched)
        else:
            # Direct path - check if file exists
            if Path(path_pattern).is_file():
                all_files.add(path_pattern)
            else:
                print(f"Warning: File not found: {path_pattern}")

    # Convert to sorted list for consistent output
    return [Path(f) for f in all_files]


class OTelTraceReplayDataGenerator(SessionGenerator, LazyLoadDataMixin):
    """
    Data generator that replays LLM requests from OpenTelemetry trace files.

    Features:
    - Processes multiple OTel JSON files from a directory
    - Each file becomes a separate session
    - Supports concurrent session replay
    - Maintains wall-clock timing with time_scale parameter
    - Enforces dependencies between requests
    - Supports model mapping or static model override
    - Output-aware: substitutes recorded assistant messages with actual LLM outputs
      for growing-context patterns (multi-turn, agent chains)
    """

    def __init__(
        self,
        api_config: APIConfig,
        config: DataConfig,
        tokenizer: Optional[CustomTokenizer],
        mp_manager: Optional[SyncManager] = None,
        base_seed: Optional[int] = None,
        num_workers: int = 1,
    ) -> None:
        super().__init__(api_config, config, tokenizer)

        if not hasattr(config, "otel_trace_replay") or config.otel_trace_replay is None:
            raise ValueError("otel_trace_replay configuration is required for OTelTraceReplayDataGenerator")

        self.otel_config = config.otel_trace_replay
        self.mp_manager = mp_manager
        self.num_workers = max(1, num_workers)
        self.base_seed = base_seed if base_seed is not None else 42

        # Determine trace files to load
        if self.otel_config.trace_directory:
            self.trace_dir: Optional[Path] = Path(self.otel_config.trace_directory)

            if not self.trace_dir.exists():
                raise ValueError(f"Trace directory does not exist: {self.trace_dir}")
            if not self.trace_dir.is_dir():
                raise ValueError(f"Trace directory path is not a directory: {self.trace_dir}")

            # Load all JSON files from directory
            self.trace_files_list = sorted(self.trace_dir.glob("*.json"))
            if not self.trace_files_list:
                raise ValueError(f"No JSON files found in {self.trace_dir}")

        elif self.otel_config.trace_files:
            # Multiple files mode
            self.trace_files_list = resolve_trace_files(self.otel_config.trace_files)
            self.trace_dir = None

            # Validate all files exist and are JSON
            for trace_file in self.trace_files_list:
                if not trace_file.exists():
                    raise ValueError(f"Trace file does not exist: {trace_file}")
                if not trace_file.is_file():
                    raise ValueError(f"Trace file path is not a file: {trace_file}")
                if trace_file.suffix != ".json":
                    raise ValueError(f"Trace file must be a JSON file: {trace_file}")
        else:
            raise ValueError("Either trace_directory or trace_files must be provided in otel_trace_replay config")

        # Intra-worker output registry: plain dicts + asyncio.Event, no IPC.
        self.output_registry = EventOutputRegistry()

        # Intra-worker session tracker: tracks event completions and session failures within worker.
        # Each worker has its own instance due to session-to-worker affinity.
        self.worker_tracker = WorkerSessionTracker()

        # Session completion queue: workers push (session_id, completion_data) when sessions complete.
        # Main process consumes from this queue to update state and close OTEL spans.
        # The completion_data includes a "failed" field to indicate session failure.
        if mp_manager is not None:
            self.session_completion_queue: Any = mp_manager.Queue()  # Queue for (session_id, completion_data)
        else:
            self.session_completion_queue = None

        # Load and process all OTel trace files
        self.sessions: List[OTelTraceSession] = []
        self._load_trace_files()

        # Session state tracking (LoadGen controls which sessions are active)
        self.session_graph_state: Dict[str, SessionGraphState] = {}

        if not self.sessions:
            raise ValueError("No valid OTel trace files found")

        # Build flat list of all events across all sessions for replay
        self._build_replay_schedule()

        logger.debug(f"Loaded {len(self.sessions)} sessions with {len(self.all_events)} total events")

    def _load_trace_files(self) -> None:
        """Load and process OTel JSON files."""
        logger.info(f"Loading {len(self.trace_files_list)} trace files")

        for file_index, trace_file in enumerate(self.trace_files_list):
            try:
                session = self._process_trace_file(trace_file, file_index)
                if session:
                    self.sessions.append(session)
                    event_count = len(session.graph.events)
                    logger.info(f"Loaded session {session.session_id} from {trace_file.name} with {event_count} events")
            except Exception as e:
                logger.error(f"Failed to process trace file {trace_file}: {e}")
                if not self.otel_config.skip_invalid_files:
                    raise

        # Randomize session order using base_seed for reproducibility
        random.seed(self.base_seed)
        random.shuffle(self.sessions)
        logger.info(f"Randomized session order using seed: {self.base_seed}")

        # Duplicate sessions if needed to meet total session requirements
        # self._duplicate_sessions_if_needed()

    def _duplicate_sessions_if_needed(self) -> None:
        """Duplicate sessions to ensure we have enough for high-concurrency testing.

        This is useful when the trace corpus is smaller than needed for stress testing.
        Sessions are duplicated with unique IDs to avoid conflicts.
        Target: 300 sessions (enough for most test scenarios)
        """
        target_sessions = 300
        current_count = len(self.sessions)

        if current_count >= target_sessions:
            logger.info(f"Session corpus sufficient: {current_count} sessions available (target: {target_sessions})")
            return

        # Calculate how many duplicates we need
        duplicates_needed = target_sessions - current_count
        logger.warning(
            f"Session corpus small: {current_count} sessions available. "
            f"Duplicating to reach {target_sessions} sessions for stress testing."
        )

        # Duplicate sessions in round-robin fashion
        original_sessions = list(self.sessions)
        duplicate_count = 0
        session_idx = 0

        while len(self.sessions) < target_sessions:
            # Get next session to duplicate (round-robin)
            source_session = original_sessions[session_idx % len(original_sessions)]
            session_idx += 1
            duplicate_count += 1

            # Create duplicate with unique ID
            duplicate_session = OTelTraceSession(
                session_id=f"{source_session.session_id}_dup{duplicate_count}",
                file_path=source_session.file_path,
                file_index=source_session.file_index + 10000 + duplicate_count,  # Unique file_index
                graph=source_session.graph,  # Graph can be shared (immutable)
                start_offset_ms=source_session.start_offset_ms,
            )

            self.sessions.append(duplicate_session)

        logger.info(f"Duplicated {duplicates_needed} sessions. Total sessions now: {len(self.sessions)}")

    def _process_trace_file(self, trace_file: Path, file_index: int) -> Optional[OTelTraceSession]:
        """Process a single OTel JSON trace file into a ReplayGraph session."""
        try:
            data = json.loads(trace_file.read_text(encoding="utf-8"))
        except json.JSONDecodeError as e:
            logger.error(f"Invalid JSON in {trace_file}: {e}")
            return None
        except Exception as e:
            logger.error(f"Error reading trace file {trace_file}: {e}")
            return None

        spans = data.get("spans") or []
        if not spans:
            logger.warning(f"No spans found in {trace_file}")
            return None

        try:
            raw_calls = build_raw_calls(spans, include_errors=self.otel_config.include_errors)
            if not raw_calls:
                logger.warning(f"No LLM calls found in {trace_file}")
                return None

            graph = build_graph(
                raw_calls,
                source_file=str(trace_file),
            )
        except Exception as e:
            logger.error(f"Error building graph from {trace_file}: {e}")
            return None

        # Use trace_id from first call as session_id, but make it unique by adding file_index
        # to handle cases where multiple files have the same trace_id
        base_session_id = raw_calls[0].trace_id or f"session_{file_index}"
        session_id = f"file{file_index}_{base_session_id}"

        return OTelTraceSession(
            session_id=session_id,
            file_path=trace_file,
            file_index=file_index,
            graph=graph,
        )

    def _build_replay_schedule(self) -> None:
        """Build the replay schedule using graph traversal (no time-based sorting).

        Creates event list and initializes session graph states for traversal.
        Sessions are activated on-demand based on concurrent_sessions limit.
        """
        self.all_events: List[OTelTraceReplayEvent] = []

        for session in self.sessions:
            # Initialize session graph state
            state = SessionGraphState(
                session_id=session.session_id,
                graph=session.graph,
                ready_events=set(),  # Will be populated when session is activated
                dispatched_events=set(),
                completed_events=set(),
                event_completion_times={},
                is_active=False,
                is_complete=False,
            )
            self.session_graph_state[session.session_id] = state

            # Build events for indexing (no time-based sorting)
            for event in session.graph.events.values():
                gc = event.call

                if not gc.messages:
                    logger.warning(f"Call {gc.call_id} in event {event.event_id} has no messages, skipping")
                    continue

                # Qualify event_id with session to avoid collisions
                qualified_event_id = f"{session.session_id}:{event.event_id}"
                qualified_predecessor_ids = [f"{session.session_id}:{pid}" for pid in event.predecessor_event_ids]

                # Rewrite source_event_id in input_segments
                qualified_segments = [
                    dc_replace(seg, source_event_id=f"{session.session_id}:{seg.source_event_id}")
                    if seg.source_event_id is not None
                    else seg
                    for seg in gc.input_segments
                ]

                self.all_events.append(
                    OTelTraceReplayEvent(
                        call_id=gc.call_id,
                        event_id=qualified_event_id,
                        file_index=session.file_index,
                        t_start_ms=0,  # Not used in graph traversal
                        t_end_ms=0,  # Not used in graph traversal
                        model=gc.model,
                        messages=gc.messages,  # type: ignore[arg-type]
                        expected_output=gc.expected_output,
                        input_segments=qualified_segments,
                        expected_output_tokens=gc.expected_output_tokens,
                        temperature=gc.temperature,
                        max_tokens_recorded=gc.max_tokens_recorded,
                        predecessor_event_ids=qualified_predecessor_ids,
                        wait_ms=event.wait_ms,
                    )
                )

        # NO SORTING - events accessed by index via mappings

        logger.info(
            f"Built replay schedule: {len(self.all_events)} events across "
            f"{len(self.sessions)} sessions (graph-based traversal)"
        )

    def _get_effective_model(self, recorded_model: str) -> str:
        """Get the effective model name for a request."""
        if self.otel_config.use_static_model:
            # Use static model from config
            return self.otel_config.static_model_name
        else:
            # Use model mapping if provided
            if self.otel_config.model_mapping:
                return self.otel_config.model_mapping.get(recorded_model, recorded_model)
            return recorded_model

    def get_supported_apis(self) -> List[APIType]:
        """Return supported API types."""
        return [APIType.Chat]

    def is_preferred_worker_requested(self) -> bool:
        """Always True: all events of a session must run on the same worker for dependency waiting to work."""
        return True

    def get_session_count(self) -> int:
        """Return the total number of sessions (trace files) available for replay."""
        return len(self.sessions)

    def get_session_event_indices(self, session_index: int) -> List[int]:
        """Get the event indices for a specific session.

        Args:
            session_index: Index of the session (0-based)

        Returns:
            List of event indices (into self.all_events) that belong to this session

        Raises:
            IndexError: If session_index is out of range
        """
        if session_index < 0 or session_index >= len(self.sessions):
            raise IndexError(f"Session index {session_index} out of range (total: {len(self.sessions)})")

        session = self.sessions[session_index]
        # Find all events that belong to this session by matching file_index
        return [i for i, event in enumerate(self.all_events) if event.file_index == session.file_index]

    def get_session_info(self, session_index: int) -> Dict[str, Any]:
        """Get information about a specific session.

        Args:
            session_index: Index of the session (0-based)

        Returns:
            Dictionary with session metadata
        """
        if session_index < 0 or session_index >= len(self.sessions):
            raise IndexError(f"Session index {session_index} out of range (total: {len(self.sessions)})")

        session = self.sessions[session_index]
        event_indices = self.get_session_event_indices(session_index)

        return {
            "session_id": session.session_id,
            "file_path": str(session.file_path),
            "file_index": session.file_index,
            "num_events": len(event_indices),
            "num_graph_events": len(session.graph.events),
            "start_offset_ms": session.start_offset_ms,
        }

    def get_session_events(self, session_index: int) -> List[LazyLoadInferenceAPIData]:
        """Get all events for a session, all assigned to the same worker.

        Assigning a deterministic worker to every event in a session ensures that
        all events run on the same event loop, which is required for dependency
        waiting to work correctly. The assignment is based on a hash of the session
        ID, so it is stable within a single run but not across runs.
        """
        session = self.sessions[session_index]
        event_indices = self.get_session_event_indices(session_index)
        session_worker_id = abs(hash(session.session_id)) % self.num_workers
        return [LazyLoadInferenceAPIData(data_index=idx, preferred_worker_id=session_worker_id) for idx in event_indices]

    def build_session_metric(
        self,
        session_id: str,
        stage_id: int,
        start_time: float,
        end_time: float,
    ) -> SessionLifecycleMetric:
        """Build a SessionLifecycleMetric for a completed session.

        Token totals are left at 0 here and filled in later by the report
        generator once all metrics have been collected (the multiprocess
        collector only exposes metrics after the full run completes).

        Args:
            session_id: The session ID
            stage_id: The stage this session ran in
            start_time: Wall-clock epoch when the session was dispatched
            end_time: Wall-clock epoch when the session completed
        """
        state = self.session_graph_state.get(session_id)
        if state is None:
            raise ValueError(f"Unknown session: {session_id}")

        # Find the file_path for this session
        file_path = ""
        for session in self.sessions:
            if session.session_id == session_id:
                file_path = str(session.file_path)
                break

        num_events = len(state.graph.events)
        num_events_completed = len(state.completed_events)
        num_events_cancelled = state.cancelled_events if state.failed else 0

        return SessionLifecycleMetric(
            session_id=session_id,
            stage_id=stage_id,
            file_path=file_path,
            start_time=start_time,
            end_time=end_time,
            duration_sec=end_time - start_time,
            num_events=num_events,
            num_events_completed=num_events_completed,
            num_events_cancelled=num_events_cancelled,
        )

    def activate_session(self, session_id: str) -> None:
        """Internal method to activate a session (mark events as ready).

        This is called by LoadGen when it decides to start a session.
        """
        state = self.session_graph_state.get(session_id)
        if state is None:
            logger.warning(f"Attempted to activate unknown session: {session_id}")
            return

        state.is_active = True

        # Find and activate root events (no predecessors)
        root_events = {event_id for event_id, event in state.graph.events.items() if not event.predecessor_event_ids}
        state.ready_events.update(root_events)

        logger.debug(f"Activated session {session_id} with {len(root_events)} root events")

    def _process_completion_queue(self) -> None:
        """Process all pending completion notifications from the queue.

        Internal helper that drains the completion queue and updates
        session_graph_state for all completed sessions, including their failure status.
        """
        if self.session_completion_queue is None:
            return

        try:
            while True:
                completion_data = self.session_completion_queue.get_nowait()
                completed_session_id = completion_data["session_id"]

                # Update state for the completed session
                completed_state = self.session_graph_state.get(completed_session_id)
                if completed_state is not None:
                    # Mark all events as completed (event_ids are already unqualified)
                    event_times = completion_data.get("event_completion_times", {})
                    for event_id, completion_time in event_times.items():
                        if event_id not in completed_state.completed_events:
                            completed_state.completed_events.add(event_id)
                            completed_state.event_completion_times[event_id] = completion_time

                    completed_state.is_complete = True
                    completed_state.failed = completion_data.get("failed", False)
                    completed_state.cancelled_events = completion_data.get("cancelled_events", 0)
                    logger.debug(
                        f"Session {completed_session_id} marked complete from queue notification "
                        f"(failed={completed_state.failed})"
                    )
        except Exception:
            # Queue is empty, no more completions to process
            pass

    def check_session_completed(self, session_id: str) -> bool:
        """Check if a specific session has completed all its events.

        Processes all pending completion notifications first, then checks
        the requested session's status.

        Args:
            session_id: The session ID to check

        Returns:
            True if all events in the session have completed, False otherwise
        """
        # Process all pending completions first
        self._process_completion_queue()

        # Then check the requested session
        state = self.session_graph_state.get(session_id)
        if state is None:
            logger.warning(f"Attempted to check unknown session: {session_id}")
            return False

        # A session is considered completed if either:
        # 1. It has completed normally (is_complete = True), OR
        # 2. It has failed (marked in shared_failed_sessions for multiprocess mode)
        if state.is_complete:
            return True

        # Check if session has failed in any worker process
        # In multiprocess mode, workers add failed sessions to shared_failed_sessions
        shared_failed = getattr(self, "shared_failed_sessions", None)
        if shared_failed is not None:
            is_failed = session_id in shared_failed
            if is_failed:
                # Mark it as complete so we don't check again
                state.is_complete = True
                logger.info(f"Session {session_id} marked as complete due to failure")
                return True

        return False

    def load_lazy_data(self, data: LazyLoadInferenceAPIData) -> InferenceAPIData:
        """Load the actual request data for a given index.

        Returns an OTelChatCompletionAPIData instance carrying the dependency
        information (predecessor_event_ids, wait_ms, input_segments). The worker
        calls wait_for_predecessors_and_substitute() on this object before
        dispatching the HTTP request, which suspends the coroutine until all
        predecessors have completed and then substitutes their outputs into the
        message list.
        """
        n = data.data_index

        if n >= len(self.all_events):
            raise IndexError(f"Event index {n} out of range (total: {len(self.all_events)})")

        event = self.all_events[n]

        # Convert messages to ChatMessage objects (substitution happens later in the worker).
        chat_messages = []
        for msg in event.messages:
            role = msg.get("role", "user")
            content = msg.get("content", "")

            # Handle content that might be a list (tool blocks)
            if isinstance(content, list):
                content_parts = []
                for block in content:
                    if isinstance(block, dict):
                        if block.get("type") == "text":
                            content_parts.append(block.get("text", ""))
                        else:
                            content_parts.append(json.dumps(block))
                    else:
                        content_parts.append(str(block))
                content = " ".join(content_parts)

            chat_messages.append(ChatMessage(role=role, content=str(content)))

        # Use expected_output_tokens (from trace) so downstream prefix matching works.
        # Fall back to config default if not available.
        max_tokens = event.expected_output_tokens or self.otel_config.default_max_tokens

        # Extract session_id and get total event count for completion detection
        session_id = event.event_id.split(":")[0] if ":" in event.event_id else event.event_id
        state = self.session_graph_state.get(session_id)
        total_events = len(state.graph.events) if state else 0

        # Return OTelChatCompletionAPIData with dependency info.
        # The worker calls wait_for_predecessors_and_substitute() before dispatching.
        # Create the actual data object with all fields
        actual_data = OTelChatCompletionAPIData(
            messages=chat_messages,
            max_tokens=max_tokens,
            event_id=event.event_id,
            registry=self.output_registry,
            worker_tracker=getattr(self, "worker_tracker", WorkerSessionTracker()),
            completion_queue=getattr(self, "session_completion_queue", None),
            total_events_in_session=total_events,
            # Pass dependency info for the worker to use during async waiting
            predecessor_event_ids=event.predecessor_event_ids,
            wait_ms=event.wait_ms,
            input_segments=event.input_segments,
            original_messages=event.messages,
            expected_output_content=event.expected_output,
            otel_context=data.otel_context,
            session_id=data.session_id,
            preferred_worker_id=data.preferred_worker_id,
        )

        return actual_data

    def cleanup_session(self, session_id: str) -> None:
        """Clean up memory for a completed session.

        Removes all event outputs, messages, and completion tracking data
        for the specified session to prevent memory leaks in long-running
        benchmarks with many sessions.

        Args:
            session_id: The session ID to clean up
        """
        state = self.session_graph_state.get(session_id)
        if state is None:
            logger.warning(f"Attempted to cleanup unknown session: {session_id}")
            return

        # Count events for logging
        event_count = len(state.graph.events)

        # Remove event outputs and messages from registry
        for event_id in state.graph.events.keys():
            qualified_event_id = f"{session_id}:{event_id}"

            # Remove from output registry
            self.output_registry._event_output_text.pop(qualified_event_id, None)
            self.output_registry._event_input_messages.pop(qualified_event_id, None)
            self.output_registry._event_signals.pop(qualified_event_id, None)

            # Completion times are tracked in worker_tracker and communicated via queue.
            # No shared state cleanup needed.

        # Remove session state
        del self.session_graph_state[session_id]

        logger.debug(f"Cleaned up session {session_id}: removed {event_count} events from memory")
