# Copyright 2025 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
OTel Trace Replay Data Generator

This module provides a data generator that replays LLM requests from OpenTelemetry trace files.
It processes OTel JSON traces, extracts LLM calls, infers dependencies, and replays them
with proper timing and dependency enforcement.

Output-aware replay
-------------------
When a call has "output" segments (i.e., a predecessor's output was injected as an assistant
message in the original trace), the replayer substitutes the recorded assistant message content
with the *actual* output generated by the predecessor call at replay time.

This ensures that growing-context patterns (multi-turn conversations, agent chains) are replayed
faithfully: the KV cache sees the real generated text, not the static recorded text.

The substitution is performed in `load_lazy_data` using the `EventOutputRegistry`, which maps
event_id → actual output text. All registry data is stored in per-worker plain dicts; session-to-
worker affinity ensures that the event writing an output and the events reading it always run on
the same worker process.

The actual output is captured in `SessionChatCompletionAPIData.process_response`, which overrides
the base `ChatCompletionAPIData.process_response` to register the output after each LLM call.

Cross-process coordination
---------------------------
Two orthogonal coordination problems exist in this system:

  Problem A — intra-worker, between coroutines on the same event loop:
    An event waits for its predecessor's output before building its request.
    Handled by EventOutputRegistry using plain dicts and asyncio.Event.
    No IPC involved; session-to-worker affinity makes cross-process sharing unnecessary.

  Problem B — cross-process, worker → main process:
    The main process needs to know when sessions complete for OTEL span closure and reporting.
    Workers detect session completion and push notifications via mp.Queue.

    - WorkerSessionTracker: Per-worker tracking of event completions and session failures
    - session_completion_queue: Workers push completion data when last event finishes
    - Main process consumes from queue in check_session_completed()

SessionChatCompletionAPIData holds refs to WorkerSessionTracker and completion_queue.
"""

import glob
import json
import logging
import random
from multiprocessing.managers import SyncManager
from pathlib import Path
from typing import List, Optional

from inference_perf.config import APIConfig, DataConfig
from inference_perf.datagen.replay_graph_session_datagen import (
    ReplaySession,
    ReplayGraphSessionGeneratorBase,
)
from inference_perf.datagen.otel_trace_to_replay_graph import (
    build_raw_calls,
    build_graph,
)
from inference_perf.utils.custom_tokenizer import CustomTokenizer

logger = logging.getLogger(__name__)


def resolve_trace_files(trace_files: List[str]) -> List[Path]:
    """
    Extract all relevant files from a list of paths.

    Handles two types of paths:
    1. Full path to a Otel file: /path/to/file.json
    2. Wildcard pattern: /path/to/*.json

    Args:
        trace_files: List of file paths or wildcard patterns

    Returns:
        List of resolved file paths (duplicates removed, sorted)

    Example:
        >>> paths = [
        ...     "/data/config.json",
        ...     "/logs/*.json",
        ...     "/output/**/*.json"  # recursive pattern
        ... ]
        >>> files = resolve_trace_files(paths)
    """
    all_files = set()  # Use set to avoid duplicates

    for path_pattern in trace_files:
        # Check if path contains wildcard characters
        if "*" in path_pattern or "?" in path_pattern:
            # Use glob to expand the pattern
            # recursive=True enables ** pattern for recursive matching
            matched_files = glob.glob(path_pattern, recursive=True)

            # Filter to only include files (not directories)
            for matched in matched_files:
                if Path(matched).is_file():
                    all_files.add(matched)
        else:
            # Direct path - check if file exists
            if Path(path_pattern).is_file():
                all_files.add(path_pattern)
            else:
                print(f"Warning: File not found: {path_pattern}")

    # Convert to sorted list for consistent output
    return [Path(f) for f in all_files]


class OTelTraceReplayDataGenerator(ReplayGraphSessionGeneratorBase):
    """
    Data generator that replays LLM requests from OpenTelemetry trace files.

    Features:
    - Processes multiple OTel JSON files from a directory
    - Each file becomes a separate session
    - Supports concurrent session replay
    - Maintains wall-clock timing with time_scale parameter
    - Enforces dependencies between requests
    - Supports model mapping or static model override
    - Output-aware: substitutes recorded assistant messages with actual LLM outputs
      for growing-context patterns (multi-turn, agent chains)
    """

    def __init__(
        self,
        api_config: APIConfig,
        config: DataConfig,
        tokenizer: Optional[CustomTokenizer],
        mp_manager: Optional[SyncManager] = None,
        base_seed: Optional[int] = None,
        num_workers: int = 1,
    ) -> None:
        super().__init__(api_config, config, tokenizer, mp_manager=mp_manager, base_seed=base_seed, num_workers=num_workers)

        if not hasattr(config, "otel_trace_replay") or config.otel_trace_replay is None:
            raise ValueError("otel_trace_replay configuration is required for OTelTraceReplayDataGenerator")

        self.otel_config = config.otel_trace_replay
        self.mp_manager = mp_manager
        self.num_workers = max(1, num_workers)
        self.base_seed = base_seed if base_seed is not None else 42

        # Determine trace files to load
        if self.otel_config.trace_directory:
            self.trace_dir: Optional[Path] = Path(self.otel_config.trace_directory)

            if not self.trace_dir.exists():
                raise ValueError(f"Trace directory does not exist: {self.trace_dir}")
            if not self.trace_dir.is_dir():
                raise ValueError(f"Trace directory path is not a directory: {self.trace_dir}")

            # Load all JSON files from directory
            self.trace_files_list = sorted(self.trace_dir.glob("*.json"))
            if not self.trace_files_list:
                raise ValueError(f"No JSON files found in {self.trace_dir}")

        elif self.otel_config.trace_files:
            # Multiple files mode
            self.trace_files_list = resolve_trace_files(self.otel_config.trace_files)
            self.trace_dir = None

            # Validate all files exist and are JSON
            for trace_file in self.trace_files_list:
                if not trace_file.exists():
                    raise ValueError(f"Trace file does not exist: {trace_file}")
                if not trace_file.is_file():
                    raise ValueError(f"Trace file path is not a file: {trace_file}")
                if trace_file.suffix != ".json":
                    raise ValueError(f"Trace file must be a JSON file: {trace_file}")
        else:
            raise ValueError("Either trace_directory or trace_files must be provided in otel_trace_replay config")

        sessions = self._load_trace_files()
        self.initialize_sessions(sessions)

    def _load_trace_files(self) -> List[ReplaySession]:
        """Load and process OTel JSON files."""
        logger.info(f"Loading {len(self.trace_files_list)} trace files")
        sessions: List[ReplaySession] = []

        for file_index, trace_file in enumerate(self.trace_files_list):
            try:
                session = self._process_trace_file(trace_file, file_index)
                if session:
                    sessions.append(session)
                    event_count = len(session.graph.events)
                    logger.info(f"Loaded session {session.session_id} from {trace_file.name} with {event_count} events")
            except Exception as e:
                logger.error(f"Failed to process trace file {trace_file}: {e}")
                if not self.otel_config.skip_invalid_files:
                    raise

        random.seed(self.base_seed)
        random.shuffle(sessions)
        logger.info(f"Randomized session order using seed: {self.base_seed}")
        return sessions

    def _duplicate_sessions_if_needed(self) -> None:
        """Duplicate sessions to ensure we have enough for high-concurrency testing.

        This is useful when the trace corpus is smaller than needed for stress testing.
        Sessions are duplicated with unique IDs to avoid conflicts.
        Target: 300 sessions (enough for most test scenarios)
        """
        target_sessions = 300
        current_count = len(self.sessions)

        if current_count >= target_sessions:
            logger.info(f"Session corpus sufficient: {current_count} sessions available (target: {target_sessions})")
            return

        # Calculate how many duplicates we need
        duplicates_needed = target_sessions - current_count
        logger.warning(
            f"Session corpus small: {current_count} sessions available. "
            f"Duplicating to reach {target_sessions} sessions for stress testing."
        )

        # Duplicate sessions in round-robin fashion
        original_sessions = list(self.sessions)
        duplicate_count = 0
        session_idx = 0

        while len(self.sessions) < target_sessions:
            # Get next session to duplicate (round-robin)
            source_session = original_sessions[session_idx % len(original_sessions)]
            session_idx += 1
            duplicate_count += 1

            # Create duplicate with unique ID
            duplicate_session = ReplaySession(
                session_id=f"{source_session.session_id}_dup{duplicate_count}",
                source_id=source_session.source_id,
                session_index=source_session.session_index + 10000 + duplicate_count,
                graph=source_session.graph,
                start_offset_ms=source_session.start_offset_ms,
            )

            self.sessions.append(duplicate_session)

        logger.info(f"Duplicated {duplicates_needed} sessions. Total sessions now: {len(self.sessions)}")

    def _process_trace_file(self, trace_file: Path, file_index: int) -> Optional[ReplaySession]:
        """Process a single OTel JSON trace file into a ReplayGraph session."""
        try:
            data = json.loads(trace_file.read_text(encoding="utf-8"))
        except json.JSONDecodeError as e:
            logger.error(f"Invalid JSON in {trace_file}: {e}")
            return None
        except Exception as e:
            logger.error(f"Error reading trace file {trace_file}: {e}")
            return None

        spans = data.get("spans") or []
        if not spans:
            logger.warning(f"No spans found in {trace_file}")
            return None

        try:
            raw_calls = build_raw_calls(spans, include_errors=self.otel_config.include_errors)
            if not raw_calls:
                logger.warning(f"No LLM calls found in {trace_file}")
                return None

            graph = build_graph(
                raw_calls,
                source_file=str(trace_file),
            )
        except Exception as e:
            logger.error(f"Error building graph from {trace_file}: {e}")
            return None

        # Use trace_id from first call as session_id, but make it unique by adding file_index
        # to handle cases where multiple files have the same trace_id
        base_session_id = raw_calls[0].trace_id or f"session_{file_index}"
        session_id = f"file{file_index}_{base_session_id}"

        return ReplaySession(
            session_id=session_id,
            source_id=str(trace_file),
            session_index=file_index,
            graph=graph,
        )
