{
  "api": { "type": "completion", "streaming": true, "headers": null },
  "data":
    {
      "type": "shared_prefix",
      "path": null,
      "input_distribution": null,
      "output_distribution": null,
      "shared_prefix":
        {
          "num_groups": 83,
          "num_prompts_per_group": 3,
          "system_prompt_len": 8000,
          "question_len": 1000,
          "output_len": 1000,
        },
    },
  "load":
    {
      "type": "constant",
      "interval": 15.0,
      "stages":
        [
          { "rate": 9.0, "duration": 25 },
          { "rate": 2.0, "duration": 60 },
          { "rate": 5.0, "duration": 60 },
          { "rate": 8.0, "duration": 60 },
          { "rate": 10.0, "duration": 60 },
          { "rate": 15.0, "duration": 60 },
          { "rate": 20.0, "duration": 60 },
          { "rate": 25.0, "duration": 60 },
          { "rate": 30.0, "duration": 60 },
          { "rate": 40.0, "duration": 60 },
        ],
      "sweep": null,
      "num_workers": 32,
      "worker_max_concurrency": 2000,
      "worker_max_tcp_connections": 2500,
    },
  "metrics":
    {
      "type": "prometheus",
      "prometheus":
        {
          "scrape_interval": 15,
          "url": "http://localhost:9090/",
          "filters": [],
          "google_managed": false,
        },
    },
  "report":
    {
      "request_lifecycle":
        { "summary": true, "per_stage": true, "per_request": false },
      "prometheus": { "summary": true, "per_stage": false },
    },
  "storage":
    {
      "local_storage":
        { "path": "reports-20250927-170805", "report_file_prefix": null },
      "google_cloud_storage":
        {
          "path": "estimate-sho1",
          "report_file_prefix": null,
          "bucket_name": "bobgkeinference",
        },
      "simple_storage_service": null,
    },
  "server":
    {
      "type": "vllm",
      "model_name": "meta-llama/Llama-3.1-70B-Instruct",
      "base_url": "http://35.208.15.174:80",
      "ignore_eos": true,
      "api_key": null,
    },
  "tokenizer":
    {
      "pretrained_model_name_or_path": "meta-llama/Llama-3.1-70B-Instruct",
      "trust_remote_code": null,
      "token": null,
    },
}
