# Copyright 2025 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
OTel Trace Replay Data Generator

This module provides a data generator that replays LLM requests from OpenTelemetry trace files.
It processes OTel JSON traces, extracts LLM calls, infers dependencies, and replays them
with proper timing and dependency enforcement.

Output-aware replay
-------------------
When a call has "output" segments (i.e., a predecessor's output was injected as an assistant
message in the original trace), the replayer substitutes the recorded assistant message content
with the *actual* output generated by the predecessor call at replay time.

This ensures that growing-context patterns (multi-turn conversations, agent chains) are replayed
faithfully: the KV cache sees the real generated text, not the static recorded text.

The substitution is performed in `load_lazy_data` using the `EventOutputRegistry`, which maps
event_id → actual output text. All registry data is stored in per-worker plain dicts; session-to-
worker affinity ensures that the event writing an output and the events reading it always run on
the same worker process.

The actual output is captured in `SessionChatCompletionAPIData.process_response`, which overrides
the base `ChatCompletionAPIData.process_response` to register the output after each LLM call.

Cross-process coordination
---------------------------
Two orthogonal coordination problems exist in this system:

  Problem A — intra-worker, between coroutines on the same event loop:
    An event waits for its predecessor's output before building its request.
    Handled by EventOutputRegistry using plain dicts and asyncio.Event.
    No IPC involved; session-to-worker affinity makes cross-process sharing unnecessary.

  Problem B — cross-process, worker → main process:
    The main process needs to know when sessions complete for OTEL span closure and reporting.
    Workers detect session completion and push notifications via mp.Queue.

    - WorkerSessionTracker: Per-worker tracking of event completions and session failures
    - session_completion_queue: Workers push completion data when last event finishes
    - Main process consumes from queue in check_session_completed()

SessionChatCompletionAPIData holds refs to WorkerSessionTracker and completion_queue.
"""

import glob
import json
import logging
import random
from multiprocessing.managers import SyncManager
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional, Union, cast
from datasets import load_dataset, Dataset
from inference_perf.config import APIConfig, DataConfig
from inference_perf.datagen.replay.replay_graph_session_datagen import (
    ReplaySession,
    ReplayGraphSessionGeneratorBase,
)
from inference_perf.datagen.replay.otel_trace_to_replay_graph import (
    build_raw_calls,
    build_graph,
)
from inference_perf.utils.custom_tokenizer import CustomTokenizer
from inference_perf.apis import InferenceAPIData, LazyLoadInferenceAPIData

logger = logging.getLogger(__name__)


def resolve_trace_files(trace_files: List[str]) -> List[Path]:
    """
    Extract all relevant files from a list of paths.

    Handles two types of paths:
    1. Full path to a Otel file: /path/to/file.json
    2. Wildcard pattern: /path/to/*.json

    Args:
        trace_files: List of file paths or wildcard patterns

    Returns:
        List of resolved file paths (duplicates removed, sorted)

    Example:
        >>> paths = [
        ...     "/data/config.json",
        ...     "/logs/*.json",
        ...     "/output/**/*.json"  # recursive pattern
        ... ]
        >>> files = resolve_trace_files(paths)
    """
    all_files = set()  # Use set to avoid duplicates

    for path_pattern in trace_files:
        # Check if path contains wildcard characters
        if "*" in path_pattern or "?" in path_pattern:
            # Use glob to expand the pattern
            # recursive=True enables ** pattern for recursive matching
            matched_files = glob.glob(path_pattern, recursive=True)

            # Filter to only include files (not directories)
            for matched in matched_files:
                if Path(matched).is_file():
                    all_files.add(matched)
        else:
            # Direct path - check if file exists
            if Path(path_pattern).is_file():
                all_files.add(path_pattern)
            else:
                print(f"Warning: File not found: {path_pattern}")

    # Convert to sorted list for consistent output
    return [Path(f) for f in all_files]


def _validate_dataset_schema(dataset: Any, dataset_path: str) -> None:
    """Validate that a dataset has the required schema for OTel trace replay.

    Args:
        dataset: The loaded dataset (HuggingFace Dataset or Dataset.from_list)
        dataset_path: Dataset identifier for error messages

    Raises:
        ValueError: If schema validation fails
    """
    if len(dataset) == 0:
        raise ValueError(f"No data found in HuggingFace dataset '{dataset_path}'")

    if "spans" not in dataset[0]:
        raise ValueError(f"Dataset '{dataset_path}' is missing the required 'spans' field.")

    logger.info(f"Schema validation passed for dataset '{dataset_path}'")


def _normalize_file_trace(data: Dict[str, Any], source_name: str, source_path: str) -> Dict[str, Any]:
    """Normalize a local OTel JSON trace to align with the HF dataset schema.

    Local files have:  trace_id, span_count, collected_at, spans
    HF records have:   harness, benchmark, models, session_id, source_id, max_tokens, total_tokens, spans

    - session_id: derived from trace_id, or filename stem as fallback
    - source_id: full file path, used for traceability in metrics and graph serialization
    - harness/benchmark: set to "unknown" (no equivalent in local files)
    - models: extracted from gen_ai.request.model span attributes (deduplicated)
    - max_tokens: max tokens (input+output) in a single span — used to verify the target model's context window is large enough to replay the trace
    - total_tokens: sum of tokens (input+output) across all spans

    Args:
        data: Raw trace data loaded from a local JSON file
        source_name: Filename, used to derive a fallback session_id
        source_path: Full file path, stored as source_id for traceability

    Returns:
        A new dict with HF-schema fields added (existing fields preserved)
    """
    normalized = dict(data)

    if "session_id" not in normalized:
        normalized["session_id"] = normalized.get("trace_id") or Path(source_name).stem

    normalized["source_id"] = source_path

    if "harness" not in normalized:
        normalized["harness"] = "unknown"

    if "benchmark" not in normalized:
        normalized["benchmark"] = "unknown"

    if "models" not in normalized:
        normalized["models"] = list(
            {
                model
                for span in normalized.get("spans", [])
                if (model := span.get("attributes", {}).get("gen_ai.request.model"))
            }
        )

    if "max_tokens" not in normalized or "total_tokens" not in normalized:
        max_tokens = 0
        total_tokens = 0
        for span in normalized.get("spans", []):
            input_tokens = span.get("attributes", {}).get("gen_ai.usage.input_tokens", 0)
            output_tokens = span.get("attributes", {}).get("gen_ai.usage.output_tokens", 0)
            span_tokens = input_tokens + output_tokens
            if span_tokens > max_tokens:
                max_tokens = span_tokens
            total_tokens += span_tokens
        if "max_tokens" not in normalized:
            normalized["max_tokens"] = max_tokens
        if "total_tokens" not in normalized:
            normalized["total_tokens"] = total_tokens

    return normalized


def _compile_filter(filter_expr: Optional[str]) -> Optional[Callable[..., Any]]:
    """Compile a filter expression once for reuse.

    Args:
        filter_expr: Lambda expression string to evaluate (e.g., "lambda x: x['benchmark'] == 'gsm8k'"),
                    or None for no filtering

    Returns:
        Compiled filter function, or None if no filter expression provided

    Raises:
        ValueError: If filter expression is malformed or not callable

    Security Note:
        This uses eval() on user-provided input. This is acceptable for a local benchmarking tool
        where the operator controls the configuration, but the filter expression should be treated
        as trusted input only. Do not expose this to untrusted users.
    """
    if not filter_expr:
        return None
    try:
        filter_func = eval(filter_expr, {"__builtins__": {}}, {})
        if not callable(filter_func):
            raise ValueError(f"Filter expression must be a callable (lambda), got: {type(filter_func).__name__}")
        return cast(Callable[..., Any], filter_func)
    except SyntaxError as e:
        raise ValueError(f"Invalid filter expression syntax '{filter_expr}': {e}") from e
    except Exception as e:
        raise ValueError(f"Failed to compile filter expression '{filter_expr}': {e}") from e


def _load_trace_file(
    trace_file: Path,
    skip_invalid: bool,
) -> Optional[Dict[str, Any]]:
    """Load a single JSON trace file. Returns None on error if skip_invalid is set."""
    try:
        return cast(Dict[str, Any], json.loads(trace_file.read_text(encoding="utf-8")))
    except Exception as e:
        logger.error(f"Failed to load {trace_file}: {e}")
        if not skip_invalid:
            raise
        return None


def _load_files_to_dataset(files: List[Path], skip_invalid: bool) -> Dataset:
    """Load a list of trace files, normalize them, and return as a Dataset."""
    rows = []
    for trace_file in files:
        data = _load_trace_file(trace_file, skip_invalid)
        if data is not None:
            rows.append(_normalize_file_trace(data, trace_file.name, str(trace_file)))
    return Dataset.from_list(rows)


def _download_hf_dataset(
    dataset_config: Union[str, Dict[str, Any]],
) -> Dataset:
    """Load HuggingFace dataset and return it as a Dataset.

    Args:
        dataset_config: Either a string path (e.g., 'Exgentic/agent-llm-traces') or a dict with:
            - path (required): HuggingFace dataset identifier
            - Any other kwargs supported by datasets.load_dataset() (e.g., revision, split, etc.)
            - If 'split' is not provided, defaults to 'train'

    Returns:
        Dataset with trace records

    Raises:
        ValueError: If dataset cannot be downloaded, doesn't contain trace data, or schema is invalid
    """
    if isinstance(dataset_config, str):
        dataset_path = dataset_config
        load_kwargs: Dict[str, Any] = {}
    elif isinstance(dataset_config, dict):
        dataset_path_value = dataset_config.get("path")
        if not isinstance(dataset_path_value, str) or not dataset_path_value:
            raise ValueError("'path' is required in hf_dataset_path dict configuration")

        dataset_path = dataset_path_value
        if "filter" in dataset_config:
            logger.warning("'filter' in hf_dataset_path dict is ignored; use the top-level 'filter' field instead")
        load_kwargs = {k: v for k, v in dataset_config.items() if k not in ("path", "filter")}
    else:
        raise ValueError(f"hf_dataset_path must be a string or dict, got {type(dataset_config)}")

    load_kwargs = dict(load_kwargs)  # copy before mutating
    try:
        logger.info(f"Loading HuggingFace dataset: {dataset_path} with {load_kwargs.items()}")

        split = load_kwargs.pop("split", "train")
        dataset = load_dataset(dataset_path, split=split, **load_kwargs)

        _validate_dataset_schema(dataset, dataset_path)
        logger.info(f"Loaded {len(dataset)} trace records from HuggingFace dataset")
        return dataset

    except Exception as e:
        error_msg = str(e)
        if "gated dataset" in error_msg.lower() or "authenticated" in error_msg.lower():
            raise ValueError(
                f"Failed to load HuggingFace dataset '{dataset_path}': {e}\n\n"
                f"This is a gated dataset that requires authentication. To access it:\n"
                f"1. Create a HuggingFace account at https://huggingface.co/join\n"
                f"2. Request access to the dataset at https://huggingface.co/datasets/{dataset_path}\n"
                f"3. Generate an access token at https://huggingface.co/settings/tokens\n"
                f"4. Login using: huggingface-cli login\n"
                f"   Or set the HF_TOKEN environment variable with your token"
            ) from e
        else:
            raise ValueError(f"Failed to load HuggingFace dataset '{dataset_path}': {e}") from e


class OTelTraceReplayDataGenerator(ReplayGraphSessionGeneratorBase):
    """
    Data generator that replays LLM requests from OpenTelemetry trace files.

    Features:
    - Processes multiple OTel JSON files from a directory
    - Each file becomes a separate session
    - Supports concurrent session replay
    - Maintains wall-clock timing with time_scale parameter
    - Enforces dependencies between requests
    - Supports model mapping or static model override
    - Output-aware: substitutes recorded assistant messages with actual LLM outputs
      for growing-context patterns (multi-turn, agent chains)
    """

    def __init__(
        self,
        api_config: APIConfig,
        config: DataConfig,
        tokenizer: Optional[CustomTokenizer],
        mp_manager: Optional[SyncManager] = None,
        base_seed: Optional[int] = None,
        num_workers: int = 1,
    ) -> None:
        if not hasattr(config, "otel_trace_replay") or config.otel_trace_replay is None:
            raise ValueError("otel_trace_replay configuration is required for OTelTraceReplayDataGenerator")

        self.otel_config = config.otel_trace_replay

        # Pass the replay config to the parent class
        super().__init__(
            api_config,
            config,
            tokenizer,
            mp_manager=mp_manager,
            base_seed=base_seed,
            num_workers=num_workers,
            replay_config=self.otel_config,
        )

        self.mp_manager = mp_manager
        self.num_workers = max(1, num_workers)
        self.base_seed = base_seed if base_seed is not None else 42

        filter_func = _compile_filter(self.otel_config.filter)
        if filter_func:
            logger.info(f"Using filter expression: {self.otel_config.filter}")

        # Step 1: load all records into a Dataset with uniform HF schema
        if self.otel_config.trace_directory:
            trace_dir = Path(self.otel_config.trace_directory)
            if not trace_dir.exists():
                raise ValueError(f"Trace directory does not exist: {trace_dir}")
            if not trace_dir.is_dir():
                raise ValueError(f"Trace directory path is not a directory: {trace_dir}")

            trace_files = sorted(trace_dir.glob("*.json"))
            if not trace_files:
                raise ValueError(f"No JSON files found in {trace_dir}")

            dataset: Dataset = _load_files_to_dataset(trace_files, self.otel_config.skip_invalid_files)
            _validate_dataset_schema(dataset, self.otel_config.trace_directory)

        elif self.otel_config.trace_files:
            # Multiple files mode
            for path in self.otel_config.trace_files:
                if "*" not in path and "?" not in path:
                    if not Path(path).is_file():
                        raise ValueError(f"Trace file does not exist: {path}")

            trace_files = resolve_trace_files(self.otel_config.trace_files)
            if not trace_files:
                raise ValueError(f"No trace files resolved from {self.otel_config.trace_files}")

            for trace_file in trace_files:
                if not trace_file.exists():
                    raise ValueError(f"Trace file does not exist: {trace_file}")
                if not trace_file.is_file():
                    raise ValueError(f"Trace file path is not a file: {trace_file}")
                if trace_file.suffix != ".json":
                    raise ValueError(f"Trace file must be a JSON file: {trace_file}")

            dataset = _load_files_to_dataset(trace_files, self.otel_config.skip_invalid_files)
            _validate_dataset_schema(dataset, str(self.otel_config.trace_files))

        elif self.otel_config.hf_dataset_path:
            dataset = _download_hf_dataset(self.otel_config.hf_dataset_path)

        else:
            raise ValueError(
                "Either trace_directory, trace_files, or hf_dataset_path must be provided in otel_trace_replay config"
            )

        logger.info(f"Loaded {len(dataset)} records")

        # Step 2: apply filter once across all sources
        if filter_func:
            original_size = len(dataset)
            dataset = dataset.filter(filter_func)
            logger.info(f"Filter applied: {original_size} -> {len(dataset)} records")

        # Keep the dataset memory-mapped and read rows ONE AT A TIME on demand in
        # _build_session. We deliberately do NOT materialize all rows (their spans) into
        # Python memory here — for large corpora that is tens of GB resident in the parent
        # (and inherited by every forked worker). Only the small id columns are read upfront
        # to derive stable session IDs; the heavy spans stay on disk until a session is built.
        self._dataset = dataset
        num_rows = len(dataset)

        cols = dataset.column_names
        session_id_col = list(dataset["session_id"]) if "session_id" in cols else [None] * num_rows
        source_id_col = list(dataset["source_id"]) if "source_id" in cols else [None] * num_rows

        # Shuffle a permutation of row indices (not the rows themselves) so order is stable
        # and reproducible without holding any span data.
        order = list(range(num_rows))
        random.seed(self.base_seed)
        random.shuffle(order)
        self._row_order = order  # slot -> dataset row index
        logger.info(f"Randomized session order using seed: {self.base_seed}")

        # Derive session IDs (stable, independent of graph build) so get_session_count()
        # works immediately and duplicate_sessions_target can expand at the ID level.
        base_ids = [f"trace{slot}_{session_id_col[row] or f'session_{slot}'}" for slot, row in enumerate(order)]
        self._source_ids = [source_id_col[row] for row in order]  # slot -> source_id (or None)

        # Expand for duplicate_sessions_target: append (id, source_slot) pairs.
        # _source_indices[i] is None for real slots, or the source slot to copy for duplicates.
        session_ids = list(base_ids)
        self._source_indices: List[Optional[int]] = [None] * len(base_ids)
        target = self.otel_config.duplicate_sessions_target
        if target is not None and len(base_ids) < target:
            original_count = len(base_ids)
            dup_count = 0
            while len(session_ids) < target:
                src = dup_count % original_count
                dup_count += 1
                session_ids.append(f"{base_ids[src]}_dup{dup_count}")
                self._source_indices.append(src)
            logger.warning(
                f"Session corpus small: {original_count} sessions available. "
                f"Duplicating to reach {target} sessions for stress testing."
            )
            logger.info(f"Duplicated {dup_count} sessions. Total sessions now: {len(session_ids)}")
        elif target is not None:
            logger.info(f"Session corpus sufficient: {len(base_ids)} sessions available (target: {target})")

        self.initialize_sessions_lazy(session_ids)

    def _build_session(self, session_index: int) -> Optional[ReplaySession]:
        """Build one session's graph on demand (called by _ensure_session_built).

        Reads the single underlying dataset row from disk (memory-mapped) for this slot,
        builds the graph, and returns it — the row's spans are never retained beyond this
        call. For a duplicate slot, reads the source slot's row and relabels with the
        duplicate's session_id (graph content identical; the _dup suffix drives random-string
        injection in _build_session_schedule).
        """
        source_idx = self._source_indices[session_index]
        slot = source_idx if source_idx is not None else session_index
        row_index = self._row_order[slot]
        row = cast(Dict[str, Any], dict(self._dataset[row_index]))
        source_id = self._source_ids[slot] or self._session_ids[session_index]
        return self._process_trace_data(row, session_index, session_id=self._session_ids[session_index], source_id=source_id)

    def _process_trace_data(
        self,
        data: Dict[str, Any],
        trace_index: int,
        session_id: str,
        source_id: str,
    ) -> Optional[ReplaySession]:
        """Build a ReplaySession from one raw trace row dict."""
        spans = data.get("spans") or []
        if not spans:
            logger.warning(f"No spans found in {session_id}")
            return None

        try:
            raw_calls, _ = build_raw_calls(spans, include_errors=self.otel_config.include_errors)
            if not raw_calls:
                logger.warning(f"No LLM calls found in {session_id}")
                return None
            graph = build_graph(raw_calls, source_file=source_id)
        except Exception as e:
            logger.error(f"Error building graph from {session_id}: {e}", exc_info=True)
            return None

        return ReplaySession(
            session_id=session_id,
            source_id=source_id,
            session_index=trace_index,
            graph=graph,
        )

    def load_lazy_data(self, data: LazyLoadInferenceAPIData) -> InferenceAPIData:
        api_data = super().load_lazy_data(data)

        event = self._resolve_event(data)
        session_id = event.event_id.split(":")[0] if ":" in event.event_id else event.event_id
        raw_event_id = event.event_id.split(":", 1)[1] if ":" in event.event_id else event.event_id
        state = self.session_graph_state.get(session_id)
        gc = state.graph.events[raw_event_id].call if state and raw_event_id in state.graph.events else None

        if gc:
            # Ensure we have a dict to query, even if the span had no extra attributes
            attributes = gc.attributes or {}
            headers = {}
            labels = {}

            if self.otel_config.attribute_to_header_map:
                for attr_key, header_name in self.otel_config.attribute_to_header_map.items():
                    val = attributes.get(attr_key)
                    if val is None:
                        val = "default"
                    headers[header_name] = str(val)

            if self.otel_config.attribute_to_label_map:
                for attr_key, label_name in self.otel_config.attribute_to_label_map.items():
                    val = attributes.get(attr_key)
                    if val is None:
                        val = "default"
                    labels[label_name] = str(val)

            if headers:
                if api_data.headers is None:
                    api_data.headers = {}
                api_data.headers.update(headers)

            if labels:
                if api_data.labels is None:
                    api_data.labels = {}
                api_data.labels.update(labels)

        return api_data
