# Copyright 2026 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Weka Trace Replay Data Generator.

This module provides a data generator that replays Weka KV-cache-tester traces
(e.g., from Hugging Face semianalysisai/cc-traces-weka-*).

KV-Cache Fidelity & Prompt Reconstruction
-----------------------------------------
Weka traces record conversation sessions as a sequence of block hash IDs (representing fixed-size
token blocks, e.g. 16 tokens/block). They do not store the original raw text prompts or completions.
To evaluate the KV-cache scheduler/performance of a target server under identical hit/miss conditions,
the generator must reconstruct conversation prompt text that tokenizes to the exact sequence of block
hashes recorded in the trace.

1. Turn-by-Turn Reconstructor:
   For every request (turn) in a session, the generator uses a deterministic `HashIdRandomGenerator`
   seeded with a combination of base seed, conversation ID, and block hash ID. It samples words from
   a static, public domain corpus (Shakespeare) to construct the prompt and expected assistant response text.
   This guarantees that if the same block hash ID is visited on different turns or worker processes,
   it always maps to the exact same text tokens, producing identical KV-cache keys on the server.

2. Longest Common Prefix (LCP) and Branching:
   During multi-turn conversations, the user may shift topics or backtrack. The generator compares
   the block hashes of consecutive turns (`longest_common_prefix`).
   - If Turn 1 has hashes [H1, H2, H3] and Turn 2 has [H1, H2, H4], the LCP is 2.
   - The reconstructor uses this LCP to rewind the conversation history back to the end of block 2 (H2),
     evicting the text for block H3, before appending the new prompt block H4.
   - This ensures prompt-cache structural alignment matches the trace exactly.

3. History Substitution Rationale:
   The generator pre-reconstructs assistant response text based on the output token lengths in the trace.
   During live replay, the actual text generated by the server is discarded for the purpose of history building.
   Instead, the pre-reconstructed assistant text is appended to construct subsequent turn prompts.

   - Why? If the live model deviates by even 1 token in output length, it shifts the start index of the next
     user prompt. Because KV-cache blocks are aligned on fixed boundaries, this 1-token shift would cause a
     100% cache miss on all subsequent user prompt blocks.
   - History substitution preserves the exact token offsets and boundaries, guaranteeing 100% KV-cache alignment
     under deterministic (temperature=0) benchmarks. Caveat is that this is not always possible when benchmarking
     different models. But this approach is preserved so we can resemble the KV cache tester approach for this
     replay which is what we are trying to emulate.
"""

from concurrent.futures import ProcessPoolExecutor
from concurrent.futures.process import BrokenProcessPool
from dataclasses import dataclass
import hashlib
import json
import logging
import math
import multiprocessing
import os
from pathlib import Path
import random
import re
import sys
import time
from typing import Any, Dict, List, Literal, Optional, Tuple, Union, Annotated
from multiprocessing.managers import SyncManager

from huggingface_hub import hf_hub_download
from pydantic import BaseModel, Field

from inference_perf.apis import InferenceAPIData, LazyLoadInferenceAPIData
from inference_perf.config import APIConfig, DataConfig
from inference_perf.datagen.replay.replay_graph_session_datagen import (
    ReplaySession,
    ReplayGraphSessionGeneratorBase,
)
from inference_perf.datagen.replay.otel_trace_to_replay_graph import (
    DEPENDENCY_TYPE,
    RawCall,
    build_graph,
    find_predecessors_by_text_matching,
    message_content_text,
)
from inference_perf.datagen.replay.replay_graph_types import ComplexReplayMessage, ReplayMessage
from inference_perf.utils.custom_tokenizer import CustomTokenizer

logger = logging.getLogger(__name__)


# =============================================================================
# Weka Trace Pydantic Models
# =============================================================================


class WekaNormalRequest(BaseModel):
    t: float
    type: Literal["n"]
    model: str
    input_length: int = Field(alias="in")
    output_length: int = Field(alias="out")
    hash_ids: List[int] = Field(default_factory=list)
    api_time: Optional[float] = None
    think_time: Optional[float] = None


class WekaStreamingRequest(BaseModel):
    t: float
    type: Literal["s"]
    model: str
    input_length: int = Field(alias="in")
    output_length: int = Field(alias="out")
    hash_ids: List[int] = Field(default_factory=list)
    api_time: Optional[float] = None
    think_time: Optional[float] = None
    ttft: Optional[float] = None


class WekaSubagentEntry(BaseModel):
    t: float
    type: Literal["subagent"]
    agent_id: str
    subagent_type: str
    duration_ms: Optional[int] = None
    requests: List[WekaNormalRequest] = Field(default_factory=list)
    tool_tokens: int = 0
    system_tokens: int = 0


WekaRequest = Annotated[Union[WekaNormalRequest, WekaStreamingRequest, WekaSubagentEntry], Field(discriminator="type")]


class WekaTrace(BaseModel):
    id: str
    models: List[str]
    block_size: int
    tool_tokens: int = 0
    system_tokens: int = 0
    requests: List[WekaRequest]


# =============================================================================
# Timeline Timing & Warping
# =============================================================================


@dataclass(frozen=True)
class _RequestTiming:
    timestamp_seconds: float
    delay_ms: Optional[float]


@dataclass(frozen=True)
class _IdleGap:
    raw_start: float
    raw_end: float
    shift_before: float
    cap_seconds: float
    excess_seconds: float


class _IdleGapTimeWarp:
    """Compresses request-start gaps in a trace and maps raw seconds to adjusted seconds."""

    def __init__(self, request_starts: List[float], cap_seconds: float):
        self._gaps: List[_IdleGap] = []
        sorted_starts = sorted(request_starts)
        if not sorted_starts:
            return

        prev_start = sorted_starts[0]
        cumulative_shift = 0.0
        for start in sorted_starts[1:]:
            gap_seconds = start - prev_start
            if gap_seconds > cap_seconds:
                excess = gap_seconds - cap_seconds
                self._gaps.append(
                    _IdleGap(
                        raw_start=prev_start,
                        raw_end=start,
                        shift_before=cumulative_shift,
                        cap_seconds=cap_seconds,
                        excess_seconds=excess,
                    )
                )
                cumulative_shift += excess
            prev_start = start

    def map(self, t_seconds: float) -> float:
        shift = 0.0
        for gap in self._gaps:
            if t_seconds < gap.raw_start:
                return t_seconds - gap.shift_before
            if t_seconds < gap.raw_end:
                local = t_seconds - gap.raw_start
                if local <= gap.cap_seconds:
                    return t_seconds - gap.shift_before
                return gap.raw_start - gap.shift_before + gap.cap_seconds
            shift = gap.shift_before + gap.excess_seconds
        return t_seconds - shift


# =============================================================================
# Hash-ID Based Prompt Synthesis
# =============================================================================


class HashIdRandomGenerator:
    """Deterministic random generator scoped per (trace_id, hash_id)."""

    def __init__(self, base_seed: int):
        self.base_seed = base_seed
        self._trace_id: str = ""
        self._rng = random.Random()

    def set_trace_id(self, trace_id: str) -> None:
        self._trace_id = trace_id

    def reseed_for_hash_id(self, hash_id: int) -> None:
        seed_bytes = hashlib.sha256(f"{self.base_seed}:{self._trace_id}:{hash_id}".encode()).digest()
        self._rng.seed(int.from_bytes(seed_bytes[:8], "big"))

    def randrange(self, stop: int) -> int:
        return self._rng.randrange(stop)

    def choice(self, seq: list[Any]) -> Any:
        return self._rng.choice(seq)


def sample_tokens_from_corpus(
    corpus: List[int],
    num_tokens: int,
    rng_to_use: HashIdRandomGenerator,
    sep_token: Optional[int] = None,
) -> List[int]:
    """Sample tokens from the pre-tokenized corpus using the provided RNG."""
    corpus_len = len(corpus)
    tokens: List[int] = []

    if sep_token is not None:
        tokens.append(sep_token)
        num_tokens -= 1

    start = rng_to_use.randrange(corpus_len)
    end = start + num_tokens

    if end <= corpus_len:
        tokens.extend(corpus[start:end])
    else:
        tokens.extend(corpus[start:])
        tokens.extend(corpus[: end - corpus_len])

    return tokens


# =============================================================================
# Conversation Reconstructor
# =============================================================================


@dataclass
class RoleSegment:
    role: Literal["system", "user", "assistant"]
    block_start: int
    block_count: int
    tokens: List[int]
    content: str


def longest_common_prefix(prev_hash_ids: List[int], curr_hash_ids: List[int]) -> int:
    n = min(len(prev_hash_ids), len(curr_hash_ids))
    for i in range(n):
        if prev_hash_ids[i] != curr_hash_ids[i]:
            return i
    return n


def truncate_synth_buf_at_block(
    segments: List[RoleSegment],
    target_blocks: int,
    block_size: int,
    decode_tokens_to_text: Any,
    prev_partial_tail: int = 0,
) -> Optional[int]:
    if target_blocks <= 0:
        had_segments = len(segments) > 0
        segments.clear()
        return 0 if had_segments else None

    cursor = 0
    for i, seg in enumerate(segments):
        if cursor + seg.block_count < target_blocks:
            cursor += seg.block_count
            continue
        if cursor + seg.block_count == target_blocks:
            disturbed: Optional[int] = None
            if prev_partial_tail > 0 and len(seg.tokens) > 0:
                stripped_n = min(prev_partial_tail, len(seg.tokens))
                seg.tokens = seg.tokens[:-stripped_n]
                seg.content = decode_tokens_to_text(seg.tokens)
                disturbed = i
            deleted_past_boundary = i + 1 < len(segments)
            del segments[i + 1 :]
            if disturbed is None and deleted_past_boundary:
                disturbed = i + 1
            return disturbed
        if cursor == target_blocks:
            del segments[i:]
            return i
        kept_blocks = target_blocks - cursor
        kept_tokens_n = min(len(seg.tokens), kept_blocks * block_size)
        seg.block_count = kept_blocks
        seg.tokens = seg.tokens[:kept_tokens_n]
        seg.content = decode_tokens_to_text(seg.tokens)
        del segments[i + 1 :]
        return i
    return None


class ConversationReconstructor:
    """Reconstructs turn-by-turn prompts and completions deterministically."""

    def __init__(
        self,
        block_size: int,
        decode_block_tokens: Any,
        sample_partial_tail_tokens: Any,
        decode_tokens_to_text: Any,
    ):
        self.block_size = block_size
        self.decode_block_tokens = decode_block_tokens
        self.sample_partial_tail_tokens = sample_partial_tail_tokens
        self.decode_tokens_to_text = decode_tokens_to_text
        self._segments: List[RoleSegment] = []
        self._last_disturbance_at: Optional[int] = None

    def init_turn_0(
        self,
        hash_ids: List[int],
        in_tokens: int,
        tool_tokens: int,
        system_tokens: int,
        seed: str,
    ) -> None:
        bs = self.block_size
        m_full = in_tokens // bs
        partial_tail_tokens_n = in_tokens - m_full * bs
        covered_blocks = min(m_full, len(hash_ids))
        missing_block_tokens = (m_full - covered_blocks) * bs

        cursor = 0
        segs: List[RoleSegment] = []

        if tool_tokens > 0 or system_tokens > 0:
            prefix_tokens = tool_tokens + system_tokens
            prefix_blocks = math.ceil(prefix_tokens / bs)
            if prefix_blocks > 0:
                if prefix_blocks > len(hash_ids):
                    # Fallback or clamp if missing prefix hash blocks
                    prefix_blocks = len(hash_ids)
                if prefix_blocks > 0:
                    seg_tokens = self.decode_block_tokens(hash_ids[cursor : cursor + prefix_blocks])
                    segs.append(
                        RoleSegment(
                            role="system",
                            block_start=cursor,
                            block_count=prefix_blocks,
                            tokens=seg_tokens,
                            content=self.decode_tokens_to_text(seg_tokens),
                        )
                    )
                    cursor += prefix_blocks

        user_blocks = covered_blocks - cursor
        user_tokens = self.decode_block_tokens(hash_ids[cursor : cursor + user_blocks])
        synth_tail_n = missing_block_tokens + partial_tail_tokens_n
        if synth_tail_n > 0:
            user_tokens.extend(self.sample_partial_tail_tokens(synth_tail_n, seed))
        segs.append(
            RoleSegment(
                role="user",
                block_start=cursor,
                block_count=user_blocks,
                tokens=user_tokens,
                content=self.decode_tokens_to_text(user_tokens),
            )
        )

        self._segments = segs
        self._last_disturbance_at = None

    def advance_turn(
        self,
        prev_hash_ids: List[int],
        prev_in_tokens: int,
        prev_out_tokens: int,
        curr_hash_ids: List[int],
        curr_in_tokens: int,
        seed: str,
    ) -> None:
        bs = self.block_size
        m_curr = len(curr_hash_ids)
        m_curr_full = curr_in_tokens // bs
        missing_block_tokens = max(0, (m_curr_full - m_curr) * bs)
        lcp = longest_common_prefix(prev_hash_ids, curr_hash_ids)
        prev_partial_tail = prev_in_tokens % bs

        truncate_disturbance = truncate_synth_buf_at_block(
            self._segments,
            lcp,
            bs,
            decode_tokens_to_text=self.decode_tokens_to_text,
            prev_partial_tail=prev_partial_tail,
        )
        self._last_disturbance_at = truncate_disturbance

        new_blocks = curr_hash_ids[lcp:m_curr]
        new_partial_tail_n = curr_in_tokens % bs
        new_region_tokens = self.decode_block_tokens(new_blocks)
        synth_tail_n = missing_block_tokens + new_partial_tail_n
        if synth_tail_n > 0:
            new_region_tokens.extend(self.sample_partial_tail_tokens(synth_tail_n, seed))
        new_blocks_count = m_curr - lcp

        asst_blocks_target = math.ceil(prev_out_tokens / bs) if prev_out_tokens > 0 else 0
        asst_blocks = min(asst_blocks_target, new_blocks_count)
        asst_emit_size = asst_blocks * bs

        cursor = lcp
        if asst_blocks > 0:
            asst_tokens = new_region_tokens[:asst_emit_size]
            self._segments.append(
                RoleSegment(
                    role="assistant",
                    block_start=cursor,
                    block_count=asst_blocks,
                    tokens=asst_tokens,
                    content=self.decode_tokens_to_text(asst_tokens),
                )
            )
            cursor += asst_blocks

        user_blocks = new_blocks_count - asst_blocks
        user_tokens = new_region_tokens[asst_emit_size:]
        if len(user_tokens) > 0:
            self._segments.append(
                RoleSegment(
                    role="user",
                    block_start=cursor,
                    block_count=user_blocks,
                    tokens=user_tokens,
                    content=self.decode_tokens_to_text(user_tokens),
                )
            )

    def snapshot_messages(self) -> List[Dict[str, str]]:
        return [{"role": s.role, "content": s.content} for s in self._segments]


# =============================================================================
# Intermediate Reconstruction Plan Representations
# =============================================================================


@dataclass
class _ParentPlan:
    trace_id: str
    normals: List[Tuple[int, Union[WekaNormalRequest, WekaStreamingRequest]]]
    subagents: List[Tuple[int, WekaSubagentEntry]]
    block_size: int


@dataclass
class _ChildPlan:
    session_id: str
    parent_trace_id: str
    subagent_index: int
    entry: WekaSubagentEntry
    stream_index: int
    stream_requests: List[WekaNormalRequest]
    block_size: int


@dataclass
class _TraceIdleTiming:
    parent_by_outer_idx: Dict[int, _RequestTiming]
    child_by_session_request: Dict[Tuple[str, int], _RequestTiming]
    subagent_end_by_outer_idx: Dict[int, float]
    subagent_start_by_outer_idx: Dict[int, float]


def _sa_end_seconds(entry: WekaSubagentEntry) -> float:
    duration = entry.duration_ms or 0
    return entry.t + duration / 1000.0


def _subagent_request_absolute_t(entry: WekaSubagentEntry, req: WekaNormalRequest) -> float:
    if req.t + 1e-6 < entry.t:
        return entry.t + req.t
    return req.t


def _pack_into_streams(requests: List[WekaNormalRequest]) -> List[List[WekaNormalRequest]]:
    sorted_reqs = sorted(requests, key=lambda r: r.t)
    streams: List[List[WekaNormalRequest]] = []
    stream_ends: List[float] = []
    for r in sorted_reqs:
        r_end = r.t + (r.api_time or 0.0)
        placed = False
        for i, end in enumerate(stream_ends):
            if end <= r.t:
                streams[i].append(r)
                stream_ends[i] = r_end
                placed = True
                break
        if not placed:
            streams.append([r])
            stream_ends.append(r_end)
    return streams


def _build_trace_idle_timing(
    plan: _ParentPlan,
    child_plans: List[_ChildPlan],
    cap_seconds: float,
) -> _TraceIdleTiming:
    if cap_seconds <= 0:
        parent_by_outer_idx = {}
        prev_t = None
        for outer_idx, req in plan.normals:
            delay_ms: Optional[float] = None if prev_t is None else (req.t - prev_t) * 1000.0
            parent_by_outer_idx[outer_idx] = _RequestTiming(req.t, delay_ms)
            prev_t = req.t

        child_by_session_request = {}
        child_plans_for_trace = [cp for cp in child_plans if cp.parent_trace_id == plan.trace_id]
        for cp in child_plans_for_trace:
            prev_child_t = None
            for k, req in enumerate(cp.stream_requests):
                t = _subagent_request_absolute_t(cp.entry, req)
                delay_ms = None if prev_child_t is None else (t - prev_child_t) * 1000.0
                child_by_session_request[(cp.session_id, k)] = _RequestTiming(t, delay_ms)
                prev_child_t = t

        subagent_end_by_outer_idx = {outer_idx: _sa_end_seconds(entry) for outer_idx, entry in plan.subagents}
        subagent_start_by_outer_idx = {outer_idx: entry.t for outer_idx, entry in plan.subagents}
        return _TraceIdleTiming(
            parent_by_outer_idx=parent_by_outer_idx,
            child_by_session_request=child_by_session_request,
            subagent_end_by_outer_idx=subagent_end_by_outer_idx,
            subagent_start_by_outer_idx=subagent_start_by_outer_idx,
        )

    request_starts: List[float] = [req.t for _, req in plan.normals]

    # Filter child plans for this trace
    child_plans_for_trace = [cp for cp in child_plans if cp.parent_trace_id == plan.trace_id]
    for cp in child_plans_for_trace:
        for req in cp.stream_requests:
            request_starts.append(_subagent_request_absolute_t(cp.entry, req))

    warp = _IdleGapTimeWarp(request_starts, cap_seconds)
    parent_by_outer_idx = {}
    prev_t = None
    for outer_idx, req in plan.normals:
        t = warp.map(req.t)
        delay_ms = None if prev_t is None else (t - prev_t) * 1000.0
        parent_by_outer_idx[outer_idx] = _RequestTiming(t, delay_ms)
        prev_t = t

    child_by_session_request = {}
    for cp in child_plans_for_trace:
        prev_child_t = None
        for k, req in enumerate(cp.stream_requests):
            t = warp.map(_subagent_request_absolute_t(cp.entry, req))
            delay_ms = None if prev_child_t is None else (t - prev_child_t) * 1000.0
            child_by_session_request[(cp.session_id, k)] = _RequestTiming(t, delay_ms)
            prev_child_t = t

    subagent_end_by_outer_idx = {outer_idx: warp.map(_sa_end_seconds(entry)) for outer_idx, entry in plan.subagents}
    subagent_start_by_outer_idx = {outer_idx: warp.map(entry.t) for outer_idx, entry in plan.subagents}
    return _TraceIdleTiming(
        parent_by_outer_idx=parent_by_outer_idx,
        child_by_session_request=child_by_session_request,
        subagent_end_by_outer_idx=subagent_end_by_outer_idx,
        subagent_start_by_outer_idx=subagent_start_by_outer_idx,
    )


# =============================================================================
# Parallel Session Building
# =============================================================================

# Set in the parent process right before the build pool is created and cleared
# after it is drained. Forked pool workers inherit it via copy-on-write, which
# avoids pickling the generator (tokenizer, corpus) per task. Holds
# (generator, traces).
_build_ctx: Optional[Tuple["WekaTraceReplayDataGenerator", List[WekaTrace]]] = None


def _cgroup_cpu_limit(cgroup_root: Path = Path("/sys/fs/cgroup")) -> Optional[int]:
    """CPU limit imposed by the cgroup CFS quota, or None when unlimited or
    undeterminable.

    Kubernetes enforces CPU limits via the CFS quota by default (cpusets are
    used only under the static CPU manager policy), so sched_getaffinity alone
    can report far more CPUs than the pod is allowed to use.
    """
    try:
        # cgroup v2: "<quota_us> <period_us>" or "max <period_us>".
        fields = (cgroup_root / "cpu.max").read_text().split()
        if len(fields) == 2 and fields[0] != "max":
            return max(1, math.ceil(int(fields[0]) / int(fields[1])))
    except (OSError, ValueError):
        pass
    try:
        # cgroup v1: quota of -1 means unlimited.
        quota = int((cgroup_root / "cpu" / "cpu.cfs_quota_us").read_text())
        period = int((cgroup_root / "cpu" / "cpu.cfs_period_us").read_text())
        if quota > 0 and period > 0:
            return max(1, math.ceil(quota / period))
    except (OSError, ValueError):
        pass
    return None


def _first_assistant_match(
    a_out: str,
    asst_indices: List[int],
    asst_texts: List[str],
    first_exact: Dict[str, int],
    asst_concat: str,
    max_asst_len: int,
) -> Optional[Tuple[int, bool]]:
    """(message index, is_exact) of the first assistant message that equals or
    contains a_out, mirroring the generic finder's first-match-in-message-order
    rule; None when no message matches."""
    if not asst_indices:
        return None
    if a_out == "":
        # The empty string is contained in every assistant message.
        return (asst_indices[0], asst_texts[0] == "")
    if len(a_out) > max_asst_len:
        return None  # no single message can equal or contain it
    e_idx = first_exact.get(a_out)
    if e_idx is None and a_out not in asst_concat:
        return None  # contained in no message either
    for k, m_idx in enumerate(asst_indices):
        if m_idx == e_idx:
            return (m_idx, True)
        t = asst_texts[k]
        if a_out in t:
            return (m_idx, t == a_out)
    return None  # concat hit was a cross-boundary false positive


def _find_weka_predecessors(
    calls: List[RawCall],
) -> Tuple[List[Dict[int, DEPENDENCY_TYPE]], Dict[Tuple[str, str], List[int]]]:
    """Fast, semantics-identical predecessor finder for Weka-synthesized calls.

    Drop-in replacement for find_predecessors_by_text_matching. The generic
    finder calls output_matches_message for every (candidate, call, message)
    triple — hundreds of millions of Python-level calls on large traces, and
    the dominant cost of data generation. Weka-reconstructed calls only ever
    carry plain-text messages and outputs (never ComplexReplayMessage parts),
    so the identical result can be computed per call with:

    - a first-index map of assistant message texts for exact matches,
    - one C-level substring scan over the concatenated assistant texts as an
      exact reject filter for containment (concatenation cannot produce false
      negatives; rare cross-boundary false positives fall through to a precise
      per-message scan), and
    - a per-call memo so duplicate candidate output texts are resolved once.

    Match indices, dependency-dict insertion order, the exact-match
    substitution cache, and temporal fallbacks are reproduced exactly;
    equivalence is asserted against the generic finder in tests.
    """
    # This fast path reproduces only get_causal_dep's plain-text
    # CAUSAL_FULL_MATCH branch; the structured-match branches fire only for
    # ComplexReplayMessage outputs. Weka synthesizes plain ReplayMessages
    # today, but if that ever changes, defer to the generic finder rather
    # than silently dropping structured-match edges.
    if any(isinstance(c.out_message, ComplexReplayMessage) for c in calls):
        return find_predecessors_by_text_matching(calls)

    n = len(calls)
    predecessor_indices: List[Dict[int, DEPENDENCY_TYPE]] = [{} for _ in range(n)]
    output_matches_for_substitutions: Dict[Tuple[str, str], List[int]] = {}

    def get_causal_ancestors(node_idx: int) -> set[int]:
        # Identical to the closure in find_predecessors_by_text_matching.
        ancestors: set[int] = set()
        stack = [p for p, d in predecessor_indices[node_idx].items() if d != DEPENDENCY_TYPE.TEMPORAL]
        while stack:
            ancestor = stack.pop()
            if ancestor not in ancestors:
                ancestors.add(ancestor)
                stack.extend(p for p, d in predecessor_indices[ancestor].items() if d != DEPENDENCY_TYPE.TEMPORAL)
        return ancestors

    out_texts: List[Optional[str]] = [(c.out_message.text or "") if c.out_message is not None else None for c in calls]

    for i in range(1, n):
        b = calls[i]

        # Per-call index over assistant messages, in message order.
        asst_indices: List[int] = []
        asst_texts: List[str] = []
        first_exact: Dict[str, int] = {}
        for m_idx, msg in enumerate(b.messages):
            if msg.role == "assistant":
                t = message_content_text(msg)
                asst_indices.append(m_idx)
                asst_texts.append(t)
                if t not in first_exact:
                    first_exact[t] = m_idx
        asst_concat = "".join(asst_texts)
        max_asst_len = max(map(len, asst_texts), default=0)

        # Memo per call: candidate output text value -> match result.
        match_memo: Dict[str, Optional[Tuple[int, bool]]] = {}

        curr_causal_preds: Dict[int, DEPENDENCY_TYPE] = {}
        transitive_preds: set[int] = set()
        b_has_messages = bool(b.messages)

        for j in range(i - 1, -1, -1):
            if j in transitive_preds:
                continue
            a_out = out_texts[j]
            if a_out is None or not b_has_messages:
                continue  # get_causal_dep returns None for these
            if a_out in match_memo:
                res = match_memo[a_out]
            else:
                res = _first_assistant_match(a_out, asst_indices, asst_texts, first_exact, asst_concat, max_asst_len)
                match_memo[a_out] = res
            if res is None:
                continue
            m_idx, is_exact = res
            if is_exact:
                output_matches_for_substitutions.setdefault((calls[j].call_id, b.call_id), []).append(m_idx)
            curr_causal_preds[j] = DEPENDENCY_TYPE.CAUSAL_FULL_MATCH
            transitive_preds.update(get_causal_ancestors(j))

        predecessor_indices[i].update(curr_causal_preds)

        # Temporal fallback: closest earlier call that ended before b started.
        predecessor_index = None
        for j in range(i - 1, -1, -1):
            if not (b.t_start_ms < calls[j].t_end_ms):
                predecessor_index = j
                break
        if predecessor_index is not None and predecessor_index not in predecessor_indices[i]:
            predecessor_indices[i][predecessor_index] = DEPENDENCY_TYPE.TEMPORAL

    return predecessor_indices, output_matches_for_substitutions


def _estimated_trace_cost(trace: WekaTrace) -> int:
    """Rough relative cost of building one trace's session, used to order pool
    submissions largest-first. build_graph's pairwise output/input matching is
    quadratic in the number of calls, which dominates for large traces."""
    n = 0
    for req in trace.requests:
        if isinstance(req, WekaSubagentEntry):
            n += len(req.requests)
        else:
            n += 1
    return n * n


def _build_session_for_trace(trace_index: int) -> Tuple[int, Optional[ReplaySession], Optional[str]]:
    """Build one trace's ReplaySession.

    Returns (trace_index, session or None, error message or None). Errors are
    returned as strings instead of raised so per-trace skip_invalid_files
    semantics survive the process boundary. Runs inline in the serial path and
    inside forked pool workers in the parallel path; reconstruction is
    deterministic per trace (all randomness is content-keyed by
    base_seed/trace_id/hash_id), so both paths produce identical sessions.
    """
    assert _build_ctx is not None, "_build_ctx must be set before building sessions"
    generator, traces = _build_ctx
    trace = traces[trace_index]
    try:
        raw_calls = generator._reconstruct_raw_calls(trace)
        if not raw_calls:
            return (trace_index, None, None)

        graph = build_graph(raw_calls, source_file=f"weka_trace_{trace.id}", predecessor_finder=_find_weka_predecessors)

        # Make session ID unique per trace run
        session_id = f"wekatrace{trace_index}_{trace.id}"
        return (
            trace_index,
            ReplaySession(
                session_id=session_id,
                source_id=trace.id,
                session_index=trace_index,
                graph=graph,
            ),
            None,
        )
    except Exception as e:
        return (trace_index, None, f"{type(e).__name__}: {e}")


# =============================================================================
# WekaTraceReplayDataGenerator Class
# =============================================================================

# Matches the raw event ID of a subagent call (event_{i:03d}_{call_id} with
# call_id = sa_{agent_id}_s{stream}_turn_{k}). Greedy (.+) backtracks to the
# last _s<digits>_turn_<digits>, so agent IDs containing underscores parse
# correctly.
_SA_EVENT_ID_RE = re.compile(r"^event_\d+_sa_(?P<agent>.+)_s(?P<stream>\d+)_turn_\d+$")


class WekaTraceReplayDataGenerator(ReplayGraphSessionGeneratorBase):
    """Data generator that replays LLM requests from Weka trace files."""

    def __init__(
        self,
        api_config: APIConfig,
        config: DataConfig,
        tokenizer: Optional[CustomTokenizer],
        mp_manager: Optional[SyncManager] = None,
        base_seed: Optional[int] = None,
        num_workers: int = 1,
    ) -> None:
        if not hasattr(config, "weka_trace_replay") or config.weka_trace_replay is None:
            raise ValueError("weka_trace_replay configuration is required for WekaTraceReplayDataGenerator")

        self.weka_config = config.weka_trace_replay

        # Pass the replay config to the parent class
        super().__init__(
            api_config,
            config,
            tokenizer,
            mp_manager=mp_manager,
            base_seed=base_seed,
            num_workers=num_workers,
            replay_config=self.weka_config,
        )

        self.mp_manager = mp_manager
        self.num_workers = max(1, num_workers)
        self.base_seed = base_seed if base_seed is not None else 42

        # Initialize deterministic prompt corpus
        if self.tokenizer is None:
            raise ValueError("Tokenizer is required for WekaTraceReplayDataGenerator")

        if self.config and self.config.corpus_file_path:
            corpus_path = Path(self.config.corpus_file_path)
        else:
            corpus_path = Path(__file__).resolve().parents[2] / "assets" / "shakespeare.txt"

        if not corpus_path.is_file():
            raise FileNotFoundError(f"Prompt corpus file not found: {corpus_path}")

        corpus_text = corpus_path.read_text(encoding="utf-8")
        logger.info(f"Loaded prompt corpus from: {corpus_path} ({len(corpus_text)} chars)")

        base_prompt = "Pick as many lines as you can from these poem lines:\n"
        self._tokenized_corpus = self.tokenizer.get_tokenizer().encode(base_prompt + corpus_text)
        self._corpus_size = len(self._tokenized_corpus)

        # Load all WekaTrace records
        traces = self._load_weka_traces()
        sessions = self._build_sessions_from_traces(traces)
        self.initialize_sessions(sessions)

    def _load_weka_traces(self) -> List[WekaTrace]:
        """Loads traces from directories, files, or Hugging Face dataset."""
        raw_traces: List[WekaTrace] = []

        if self.weka_config.trace_directory:
            trace_dir = Path(self.weka_config.trace_directory)
            if not trace_dir.exists() or not trace_dir.is_dir():
                raise ValueError(f"Trace directory does not exist or is not a directory: {trace_dir}")
            files = sorted(trace_dir.glob("*.json"))
            if not files:
                raise ValueError(f"No JSON files found in {trace_dir}")

            for f in files:
                try:
                    blob = json.loads(f.read_text(encoding="utf-8"))
                    raw_traces.append(WekaTrace.model_validate(blob))
                except Exception as e:
                    logger.error(f"Failed to load trace {f.name}: {e}")
                    if not self.weka_config.skip_invalid_files:
                        raise

        elif self.weka_config.trace_files:
            for path in self.weka_config.trace_files:
                f = Path(path)
                if not f.is_file():
                    raise ValueError(f"Trace file does not exist: {path}")
                try:
                    blob = json.loads(f.read_text(encoding="utf-8"))
                    raw_traces.append(WekaTrace.model_validate(blob))
                except Exception as e:
                    logger.error(f"Failed to load trace {f.name}: {e}")
                    if not self.weka_config.skip_invalid_files:
                        raise

        elif self.weka_config.hf_dataset_path:
            repo_id = self.weka_config.hf_dataset_path
            if isinstance(repo_id, dict):
                repo_id = repo_id["path"]
            logger.info(f"Downloading Weka traces from Hugging Face dataset: {repo_id}")
            try:
                # Use raw file download to bypass buggy Feature-type validation in datasets
                local_path = hf_hub_download(repo_id=repo_id, filename="traces.jsonl", repo_type="dataset")
                logger.info(f"Trace file downloaded to {local_path}")

                with open(local_path, "r", encoding="utf-8") as file_stream:
                    for line_idx, line in enumerate(file_stream):
                        if line_idx >= self.weka_config.num_dataset_entries:
                            break
                        if line.strip():
                            try:
                                blob = json.loads(line)
                                raw_traces.append(WekaTrace.model_validate(blob))
                            except Exception as e:
                                logger.error(f"Failed to validate row {line_idx}: {e}")
                                if not self.weka_config.skip_invalid_files:
                                    raise
            except Exception as e:
                raise ValueError(f"Failed to load Hugging Face dataset {repo_id}: {e}") from e

        # Ensure unique trace IDs
        unique_traces: Dict[str, WekaTrace] = {}
        for trace in raw_traces:
            if trace.id in unique_traces:
                raise ValueError(f"Duplicate trace ID found: {trace.id}")
            unique_traces[trace.id] = trace

        return list(unique_traces.values())

    def _build_sessions_from_traces(self, traces: List[WekaTrace]) -> List[ReplaySession]:
        global _build_ctx
        num_workers = self._resolve_datagen_workers(len(traces))

        start = time.perf_counter()
        _build_ctx = (self, traces)
        prev_tok_parallelism = os.environ.get("TOKENIZERS_PARALLELISM")
        try:
            if num_workers > 1:
                logger.info(f"Building replay sessions for {len(traces)} traces with {num_workers} processes")
                # Submit the most expensive traces first so a giant trace does
                # not become a straggler at the tail of the queue; per-trace
                # cost is roughly quadratic in turn count. Results are
                # re-sorted by trace index below, so the output is identical
                # to the serial path.
                order = sorted(range(len(traces)), key=lambda i: -_estimated_trace_cost(traces[i]))
                # Disable the Rust tokenizer's thread pool in the parent
                # before forking (not in a post-fork worker initializer): the
                # parent already used the tokenizer, and children must not
                # inherit a live thread pool. Restored in the finally block.
                os.environ["TOKENIZERS_PARALLELISM"] = "false"
                fork_ctx = multiprocessing.get_context("fork")
                try:
                    with ProcessPoolExecutor(max_workers=num_workers, mp_context=fork_ctx) as pool:
                        results = list(pool.map(_build_session_for_trace, order))
                except BrokenProcessPool:
                    # A worker died mid-build (typically the kernel OOM killer
                    # at high worker counts). Rebuild serially instead of
                    # failing the run; output is identical, only slower.
                    logger.warning("A session-build worker process died; rebuilding all replay sessions serially")
                    results = [_build_session_for_trace(i) for i in range(len(traces))]
            else:
                results = [_build_session_for_trace(i) for i in range(len(traces))]
        finally:
            _build_ctx = None
            if prev_tok_parallelism is None:
                os.environ.pop("TOKENIZERS_PARALLELISM", None)
            else:
                os.environ["TOKENIZERS_PARALLELISM"] = prev_tok_parallelism

        sessions: List[ReplaySession] = []
        for trace_index, session, error in sorted(results, key=lambda r: r[0]):
            if error is not None:
                logger.error(f"Failed to process Weka trace {traces[trace_index].id}: {error}")
                if not self.weka_config.skip_invalid_files:
                    raise RuntimeError(f"Failed to process Weka trace {traces[trace_index].id}: {error}")
            elif session is not None:
                sessions.append(session)

        logger.info(f"Built {len(sessions)} replay sessions from {len(traces)} traces in {time.perf_counter() - start:.1f}s")

        # Shuffle sessions for stress testing
        random.seed(self.base_seed)
        random.shuffle(sessions)
        return sessions

    def _resolve_datagen_workers(self, num_traces: int) -> int:
        """Resolve the process count for parallel session building.

        Defaults to the number of CPUs available to this process (the minimum
        of the scheduling affinity and the cgroup CFS quota), capped at the
        trace count. The parallel path requires fork - pool workers inherit
        the generator (tokenizer, corpus, traces) by copy-on-write rather
        than pickling - and fork is only safe on Linux: macOS lists fork as
        available, but it is unsafe in multi-threaded processes such as this
        one (the Rust tokenizer starts threads) and Python 3.14 emits a
        DeprecationWarning for it. Non-Linux platforms fall back to serial.
        """
        if self.weka_config.datagen_workers is not None:
            n = self.weka_config.datagen_workers
        else:
            # sched_getaffinity reflects the cpuset only; Kubernetes normally
            # enforces CPU limits via the CFS quota instead, so take the
            # minimum of both.
            sched_getaffinity = getattr(os, "sched_getaffinity", None)
            n = len(sched_getaffinity(0)) if sched_getaffinity is not None else (os.cpu_count() or 1)
            quota_limit = _cgroup_cpu_limit()
            if quota_limit is not None:
                n = min(n, quota_limit)
        n = max(1, min(n, num_traces))
        if n > 1 and not sys.platform.startswith("linux"):
            logger.warning("Parallel session building requires fork and is Linux-only; building replay sessions serially")
            return 1
        return n

    def _reconstruct_raw_calls(self, trace: WekaTrace) -> List[RawCall]:
        # Per-trace deterministic scratch state. Kept local (not on self) so
        # this method is reentrant and safe to run concurrently for different
        # traces in parallel worker processes. Determinism across worker
        # counts holds only because every draw from hash_id_rng is preceded
        # by reseed_for_hash_id (see decode_block_tokens); a caller that
        # draws without reseeding (randrange via sample_tokens_from_corpus,
        # or choice) would make results depend on draw order.
        cache: Dict[int, List[int]] = {}
        hash_id_rng = HashIdRandomGenerator(self.base_seed)
        hash_id_rng.set_trace_id(trace.id)

        # Build model mappings
        model_map = self._build_model_map(trace)

        # Build Plans
        normals: List[Tuple[int, Union[WekaNormalRequest, WekaStreamingRequest]]] = []
        subagents: List[Tuple[int, WekaSubagentEntry]] = []
        for idx, req in enumerate(trace.requests):
            if isinstance(req, WekaNormalRequest | WekaStreamingRequest):
                normals.append((idx, req))
            elif isinstance(req, WekaSubagentEntry):
                subagents.append((idx, req))

        trace_bs = self.weka_config.default_block_size
        if hasattr(trace, "block_size") and trace.block_size:
            trace_bs = trace.block_size

        parent_plan = _ParentPlan(trace.id, normals, subagents, block_size=trace_bs)

        child_plans: List[_ChildPlan] = []
        for sa_index, (_, entry) in enumerate(subagents):
            streams = _pack_into_streams(list(entry.requests))
            if not streams:
                streams = [[]]
            multi = len(streams) > 1
            for stream_idx, stream_reqs in enumerate(streams):
                child_sid = f"{trace.id}::sa:{entry.agent_id}"
                if multi:
                    child_sid += f":s{stream_idx}"
                child_plans.append(
                    _ChildPlan(
                        session_id=child_sid,
                        parent_trace_id=trace.id,
                        subagent_index=sa_index,
                        entry=entry,
                        stream_index=stream_idx,
                        stream_requests=stream_reqs,
                        block_size=trace_bs,
                    )
                )

        # Time warping
        timing = _build_trace_idle_timing(parent_plan, child_plans, self.weka_config.trace_idle_gap_cap_seconds)

        # Call reconstruction helper closures
        def decode_block_tokens(hash_ids: List[int]) -> List[int]:
            tokens: List[int] = []
            for h in hash_ids:
                cached = cache.get(h)
                if cached is None:
                    hash_id_rng.reseed_for_hash_id(h)
                    start = hash_id_rng.randrange(self._corpus_size)
                    end = start + trace_bs
                    cached = self._tokenized_corpus[start:end]
                    if end > self._corpus_size:
                        cached = cached + self._tokenized_corpus[: end - self._corpus_size]
                    cache[h] = cached
                tokens.extend(cached)
            return tokens

        def sample_partial_tail_tokens(n: int, seed: str) -> List[int]:
            if n <= 0:
                return []
            digest = hashlib.sha256(seed.encode()).digest()
            offset = int.from_bytes(digest[:8], "big") % max(self._corpus_size - n, 1)
            return list(self._tokenized_corpus[offset : offset + n])

        assert self.tokenizer is not None
        tokenizer_instance = self.tokenizer

        def decode_tokens_to_text(tokens: List[int]) -> str:
            decoded = tokenizer_instance.get_tokenizer().decode(tokens)
            return decoded if isinstance(decoded, str) else " ".join(decoded)

        # Reconstruct Parent Calls
        parent_recon = ConversationReconstructor(
            block_size=trace_bs,
            decode_block_tokens=decode_block_tokens,
            sample_partial_tail_tokens=sample_partial_tail_tokens,
            decode_tokens_to_text=decode_tokens_to_text,
        )

        parent_calls: List[RawCall] = []
        for k, (outer_idx, req) in enumerate(parent_plan.normals):
            seed = f"{trace.id}:turn_{k}:partial_tail"
            if k == 0:
                parent_recon.init_turn_0(
                    hash_ids=req.hash_ids,
                    in_tokens=req.input_length,
                    tool_tokens=trace.tool_tokens,
                    system_tokens=trace.system_tokens,
                    seed=seed,
                )
            else:
                prev_req = parent_plan.normals[k - 1][1]
                parent_recon.advance_turn(
                    prev_hash_ids=prev_req.hash_ids,
                    prev_in_tokens=prev_req.input_length,
                    prev_out_tokens=prev_req.output_length,
                    curr_hash_ids=req.hash_ids,
                    curr_in_tokens=req.input_length,
                    seed=seed,
                )

            # Retrieve text messages for the prompt
            messages_dicts = parent_recon.snapshot_messages()
            messages = [ReplayMessage(role=m["role"], text=m["content"]) for m in messages_dicts]

            # Reconstruct timing
            t_timing = timing.parent_by_outer_idx[outer_idx]
            t_start_ms = int(t_timing.timestamp_seconds * 1000.0)
            t_end_ms = t_start_ms + int((req.api_time or 0.0) * 1000.0)

            # Completion is generated at next turn or placeholder if last turn
            expected_out_text = ""
            if k + 1 < len(parent_plan.normals):
                # Run lookahead advance to see what assistant message is generated
                lookahead = ConversationReconstructor(
                    block_size=trace_bs,
                    decode_block_tokens=decode_block_tokens,
                    sample_partial_tail_tokens=sample_partial_tail_tokens,
                    decode_tokens_to_text=decode_tokens_to_text,
                )
                lookahead._segments = [
                    RoleSegment(s.role, s.block_start, s.block_count, list(s.tokens), s.content)
                    for s in parent_recon._segments
                ]
                next_req = parent_plan.normals[k + 1][1]
                next_seed = f"{trace.id}:turn_{k + 1}:partial_tail"
                lookahead.advance_turn(
                    prev_hash_ids=req.hash_ids,
                    prev_in_tokens=req.input_length,
                    prev_out_tokens=req.output_length,
                    curr_hash_ids=next_req.hash_ids,
                    curr_in_tokens=next_req.input_length,
                    seed=next_seed,
                )
                # Find the assistant segment added
                for seg in reversed(lookahead._segments):
                    if seg.role == "assistant":
                        expected_out_text = seg.content
                        break
            else:
                # Last turn fallback: sample random tokens from corpus
                out_tokens = sample_partial_tail_tokens(req.output_length, f"{trace.id}:final_parent_turn_completion")
                expected_out_text = decode_tokens_to_text(out_tokens)

            out_msg = ReplayMessage(role="assistant", text=expected_out_text)

            parent_calls.append(
                RawCall(
                    call_id=f"parent_turn_{k}",
                    trace_id=trace.id,
                    t_start_ms=t_start_ms,
                    t_end_ms=t_end_ms,
                    model=model_map.get(req.model, req.model),
                    messages=messages,
                    out_message=out_msg,
                    prompt_tokens=req.input_length,
                    completion_tokens=req.output_length,
                    temperature=0.0,
                    max_tokens_recorded=req.output_length,
                )
            )

        # Reconstruct Subagent Calls
        child_calls: List[RawCall] = []
        for cp in child_plans:
            child_recon = ConversationReconstructor(
                block_size=trace_bs,
                decode_block_tokens=decode_block_tokens,
                sample_partial_tail_tokens=sample_partial_tail_tokens,
                decode_tokens_to_text=decode_tokens_to_text,
            )

            for k, creq in enumerate(cp.stream_requests):
                seed = f"{cp.session_id}:turn_{k}:partial_tail"
                if k == 0:
                    child_recon.init_turn_0(
                        hash_ids=creq.hash_ids,
                        in_tokens=creq.input_length,
                        tool_tokens=cp.entry.tool_tokens,
                        system_tokens=cp.entry.system_tokens,
                        seed=seed,
                    )
                else:
                    prev_creq = cp.stream_requests[k - 1]
                    child_recon.advance_turn(
                        prev_hash_ids=prev_creq.hash_ids,
                        prev_in_tokens=prev_creq.input_length,
                        prev_out_tokens=prev_creq.output_length,
                        curr_hash_ids=creq.hash_ids,
                        curr_in_tokens=creq.input_length,
                        seed=seed,
                    )

                messages_dicts = child_recon.snapshot_messages()
                messages = [ReplayMessage(role=m["role"], text=m["content"]) for m in messages_dicts]

                t_timing = timing.child_by_session_request[(cp.session_id, k)]
                t_start_ms = int(t_timing.timestamp_seconds * 1000.0)
                t_end_ms = t_start_ms + int((creq.api_time or 0.0) * 1000.0)

                expected_out_text = ""
                if k + 1 < len(cp.stream_requests):
                    lookahead = ConversationReconstructor(
                        block_size=trace_bs,
                        decode_block_tokens=decode_block_tokens,
                        sample_partial_tail_tokens=sample_partial_tail_tokens,
                        decode_tokens_to_text=decode_tokens_to_text,
                    )
                    lookahead._segments = [
                        RoleSegment(s.role, s.block_start, s.block_count, list(s.tokens), s.content)
                        for s in child_recon._segments
                    ]
                    next_creq = cp.stream_requests[k + 1]
                    next_seed = f"{cp.session_id}:turn_{k + 1}:partial_tail"
                    lookahead.advance_turn(
                        prev_hash_ids=creq.hash_ids,
                        prev_in_tokens=creq.input_length,
                        prev_out_tokens=creq.output_length,
                        curr_hash_ids=next_creq.hash_ids,
                        curr_in_tokens=next_creq.input_length,
                        seed=next_seed,
                    )
                    for seg in reversed(lookahead._segments):
                        if seg.role == "assistant":
                            expected_out_text = seg.content
                            break
                else:
                    out_tokens = sample_partial_tail_tokens(creq.output_length, f"{cp.session_id}:final_turn_completion")
                    expected_out_text = decode_tokens_to_text(out_tokens)

                out_msg = ReplayMessage(role="assistant", text=expected_out_text)

                child_calls.append(
                    RawCall(
                        # Call ID must match what build_graph uses, ensuring subagent uniqueness
                        call_id=f"sa_{cp.entry.agent_id}_s{cp.stream_index}_turn_{k}",
                        trace_id=trace.id,
                        t_start_ms=t_start_ms,
                        t_end_ms=t_end_ms,
                        model=model_map.get(creq.model, creq.model),
                        messages=messages,
                        out_message=out_msg,
                        prompt_tokens=creq.input_length,
                        completion_tokens=creq.output_length,
                        temperature=0.0,
                        max_tokens_recorded=creq.output_length,
                        # Final turn of this subagent stream; consumed by
                        # close_subagent_sessions to emit the session-close header.
                        extra_attributes={"session_final": True} if k + 1 == len(cp.stream_requests) else {},
                    )
                )

        # Combine all parent and child calls, then sort chronologically
        all_calls = parent_calls + child_calls
        all_calls.sort(key=lambda c: (c.t_start_ms, c.call_id))
        return all_calls

    def _build_model_map(self, trace: WekaTrace) -> Dict[str, str]:
        """Maps trace-side models to configured api_config or target models."""
        configured = self.weka_config.model_mapping or {}
        if self.weka_config.use_static_model:
            return {m: self.weka_config.static_model_name for m in trace.models}
        return configured

    def load_lazy_data(self, data: LazyLoadInferenceAPIData) -> InferenceAPIData:
        api_data = super().load_lazy_data(data)
        event_id = getattr(api_data, "event_id", "")
        internal_session_id = event_id.split(":", 1)[0] if ":" in event_id else event_id
        raw_event_id = event_id.split(":", 1)[1] if ":" in event_id else event_id
        m = _SA_EVENT_ID_RE.match(raw_event_id)
        if m and self.weka_config.subagent_separate_session_id and api_data.session_id:
            # Rewrite only the wire-visible session identity for subagent events.
            # Internal bookkeeping (predecessor waits, failure propagation, session
            # pool, eviction) keys off the event_id prefix and is unaffected.
            api_data.session_id = f"{api_data.session_id}::sa:{m.group('agent')}:s{m.group('stream')}"
        if m and self.weka_config.close_subagent_sessions:
            # Final-mark the last turn of each subagent stream so the client sends
            # the session-close header (api.session_final_header_key) with it.
            state = self.session_graph_state.get(internal_session_id)
            gc = state.graph.events[raw_event_id].call if state and raw_event_id in state.graph.events else None
            if gc is not None and gc.attributes and gc.attributes.get("session_final"):
                api_data.session_final = True
        return api_data
