name: E2E Test on change

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main
      - 'feature/**'

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Install Nix
        uses: cachix/install-nix-action@4eae8bea4afaa8f8ea8aa638ab9a7fead2f3d21e # v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: |
          nix develop -c pdm sync -d

      - name: Run end-to-end tests
        run: |
          set -euxo pipefail
          nix develop -c pdm run test:e2e -o log_cli_level=DEBUG |& tee test_e2e.out

      - name: Upload test_e2e.out
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: test_e2e
          path: test_e2e.out
